#!/bin/ksh

SLEEPTIME=$1
shift

INSTRING="$*"

BLANK20="                    "
BLANKS=""

while [ ${#BLANKS} -lt $COLUMNS ]
do
	BLANKS="${BLANKS}${BLANK20}"
done

typeset -L$(( ${COLUMNS} - 1 )) BLANKS

INSIZE=${#INSTRING}

LSIZE=$(( ${#BLANKS} - $INSIZE - 1 ))

while [ $LSIZE -gt 0 ]
do
	typeset -L${LSIZE} PFX
	PFX=$BLANKS
	print -n -r "${PFX}${INSTRING} "
	print -n "\r"
	LSIZE=$(( $LSIZE - 1 ))
	sleep $SLEEPTIME
done

print "${INSTRING} "

exit 0
