#!/bin/ksh

typeset -L1 -u U1REPLY

PLAYERS=( $* )
set -A CARDFILES

for PLAYER in ${PLAYERS[*]}
do
	CARDFILE=${PLAYER}_card.txt
	CARDFILES=( ${CARDFILES[*]} $CARDFILE )
	if [ -f $CARDFILE ]
	then
		read U1REPLY?"Overwrite $CARDFILE? "
		test $U1REPLY = Y || continue
	fi
	buzzbingo $PLAYER > $CARDFILE
done

IDXFILE=$(mktemp -t bpbgo.XXXXXXXX)
trap 'rm -f ${IDXFILE} ${IDXFILE} ; exit' 0 1 2 3 9 15


cat ${CARDFILES[*]} | grep -- "^-" | cut -f1 -d'(' |
	sort -u  > $IDXFILE

#for LINENBR in $(shuffle $(wc -l $IDXFILE))
#do
#	sed -n ${LINENBR}p $IDXFILE
#done |

shuf < $IDXFILE |
while read LINE
do
	print "\n-------------------------\nSomebody just said '${LINE#- }'"
	cat ${CARDFILES[*]} | grep -- "$LINE"
	read GET?"Next: " </dev/tty
done
