#!/bin/ksh
############################################################################## 
#	$Header: /efs/admin/home/phe.ad.leiffellague/misc/RCS/buzzphrase,v 1.6 2015/01/26 19:15:29 root Exp $
#
#	NAME		TITLE
#	buzzphrase	Philip Broughton's Systematic Buzz Phrase Projector
#
#	SYNOPSIS
#	buzzphrase [count]
#	count is number of buzz phrases to generate; defaults to 1
#	
#	DESCRIPTION
#	Mr. Broughton was a frustrated official at the U.S. Public Health
#	Service who compiled a list of garbage words that kept showing up in
#	the memos crossing his desk.  He arranged them into a matrix and
#	described a simple algorithm for selecting them more or less at random
#	to construct 1000 all-purpose chunks of bureaucratese.  This shell
#	script contains Mr. Broughton's table of words (with minor updates
#	noted below) and executes his procedure for extracting them to produce
#	impressive sounding double talk.  Happy obfuscating!
#
#	UPDATED BUZZWORDS
#	Alas, even bureaucratese has its seasons of birth, growth, and
#	senescence.  Inevitably, some terms are replaced by their next
#	generation or their opposites, others simply fade from use altogether
#	as entirely new domains of meaningless blather are opened.  In
#	recognition of this, the following replacements have been made, even as
#	we record Mr.  Broughton's original selections for posterity (or
#	possible reintroduction?).
#
#	Broughton original	Replacement
#	-------------------	-----------------
#	time-phase		paradigm
#	third-generation	object-oriented
#	responsive		proactive
#	systematized		agile
#
#	RETURN VALUE
#	none meaningful
#	
#	NOTES / CAVEATS
#	For entertainment purposes only; actual use of buzzphrases in
#	official communications may be hazardous to your reputation with 
#	professional peers, though it might boost your career.
#		
#	AUTHOR, REVIEWER
#	Leif Fellague - laf 08/18/93
#
#	$Log: buzzphrase,v $
#	Revision 1.6  2015/01/26 19:15:29  root
#	Corrected bad syntax for retrieving array size.
#
#	Revision 1.5  2015/01/26 18:37:44  root
#	Corrected an original term refernce (Broughton wrote "third generation", not "fourth-generation")
#
#	Revision 1.4  2015/01/26 18:31:45  root
#	Support variable-length word lists by replacing hard-coded 10 with array size.
#
#	Revision 1.3  2015/01/26 18:26:00  root
#	Updated word lists.
#
#	Revision 1.2  2015/01/26 18:05:24  root
#	Updated version control info to RCS format.
#
#		
##############################################################################

typeset -i NBR
if [ "$1" -gt 0 ] 2>/dev/null
then
	NBR=$1
else
	NBR=1
fi

set -A ADJ1 integrated total agile parallel functional proactive \
	optional synchronized compatible balanced

set -A ADJ2 management organizational monitored reciprocal digital \
	logistical transitional incremental object-oriented policy

set -A NOUN options flexibility capability mobility programming concept \
	paradigm projection hardware contingency

while [ $NBR -gt 0 ]
do
	echo "\
${ADJ1[RANDOM%${#ADJ1[*]}]} \
${ADJ2[RANDOM%${#ADJ2[*]}]} \
${NOUN[RANDOM%${#NOUN[*]}]}"
	NBR=${NBR}-1
done

##############################################################################
#	EOF $Source: /efs/admin/home/phe.ad.leiffellague/misc/RCS/buzzphrase,v $
##############################################################################
