#!/bin/ksh
##############################################################################
#	Copyright (c) 1993 Fellague Information Tools
#		
#	UNIX SHELL SCRIPT
#	NAME		TITLE
#	cror		rorschach generator for character displays
#
#	SYNOPSIS
#	see USAGE message below
#	
#	DESCRIPTION
#	This rorschach generator script produces symmetrical blobs on
#	character displays.  ANSI, HP, and Wyse cursor addressing is
#	supported internally through command line options, and any
#	terminal is supported on systems with the ability to emit
#	cursor addressing sequences through tput (SVR3 and fully
#	compliant descendants, maybe some others).
#
#	RETURN VALUE
#	
#	NOTES / CAVEATS
#		
#	AUTHOR, REVIEWER
#	Leif Fellague 5/21/93
#
#	MODIFICATIONS
#		
##############################################################################
#ident "%Z%MODULE: %P%  VERSION: %I%  %E%  %U%>"

unset LOOP
unset NOCLEAR
unset RESIZE
unset ANSI
unset EXITCLEAR
unset FLASH
unset UNFLASH
unset RINGBELL
SLEEPTIME=0
PATTSIZE=-1
APPNAME=`basename $0`

typeset -L1 ALTCHAR
ALTCHAR="#"

USAGE="$APPNAME [options]
options: [-a] [-h] [-p pause-time] [-s size]
         [-l] [-k] [-r] [-t] [-T x] [-c] [-b] [-f]

CURSOR POSITIONING OPTIONS (run MUCH faster by avoiding tput call)
-a = assume ANSI cursor positioning
-h = assume HP cursor positioning

OTHER OPTIONS
-p pause-time = number of seconds between repeats (only meaningful with -l)
-s size = number of iterations per pattern (default is no limit)
-l = loop mode - repeats until interrupted (only meaningful with -s)
-k = keep screen, do not erase before each iteration
-r = recalculate screen size for each pattern
-t = two-tone, switches between '#' and '.' when drawing
-T = configurable two-tone, switches between '#' and given 'x' when drawing
-c = clear screen on program termination
-b = ring bell when switching between '#' and '.' (good with -t only)
-f = make two-tone characters flash
"

while getopts p:s:lkhartT:cbf c
do
	case $c in
		a)	ANSI=true ;;
		h)	HP=true ;;
		b)	RINGBELL=`tput bel` ;;
		c)	EXITCLEAR=true ;;
		f)	FLASH=`tput blink` ; UNFLASH=`tput sgr0`;;
		k)	NOCLEAR=true ;;
		l)	LOOP=true ;;
		p)	SLEEPTIME=$OPTARG ;;
		r)	RESIZE=true ;;
		s)	PATTSIZE=$OPTARG ;;
		t)	ALTCHAR=.;;
		T)	ALTCHAR=$OPTARG ;;
		*)	print "$USAGE" >&2
			exit 1
			;;
	esac
done
shift `expr $OPTIND - 1`

if [ -n "$ANSI" ]
then
RorOut()
{
	ROW=$1
	LCOL=$2
	RCOL=$3
	OUTCHAR=$4
	print "\033[${ROW};${LCOL}H${OUTCHAR}\033[${ROW};${RCOL}H${OUTCHAR}\c"
}
elif [ -n "$HP" ]
then
RorOut()
{
	#ROW=$1
	#LCOL=$2
	#RCOL=$3
	let HROW=$1-1
	let HLCOL=$2-1
	let HRCOL=$3-1
	OUTCHAR=$4
	print \
	"\033&a${HROW}y${HLCOL}C${OUTCHAR}\033&a${HROW}y${HRCOL}C${OUTCHAR}\c"
}
elif tput cup 0 0 >/dev/null 2>&1
then
RorOut()
{
	let ROW=$1
	let LCOL=$2
	let RCOL=$3
	#let ROW=$1-1
	#let LCOL=$2-1
	#let RCOL=$3-1
	OUTCHAR=$4
	tput cup $ROW $LCOL; print "${OUTCHAR}\c"
	tput cup $ROW $RCOL; print "${OUTCHAR}\c"
}
else
	print "\a
ERROR: tput cup not supported on this system. Specify cursor positioning
type for your terminal with command line option (see below).
" >&2
	print "$USAGE" >&2
	exit 1
fi

if [ -z "$EXITCLEAR" ]
then
	if [ -n "$ANSI" ]
	then
	trap 'tput sgr0; tput cnorm; print "\033[${ROWS};0H$COUNTER  \c"; exit' 0 1 2 3 9 15
	elif [ -n "$HP" ]
	then
	trap 'tput sgr0; tput cnorm; print "\033&a${ROWS}y0C$COUNTER  \c"; exit' 0 1 2 3 9 15
	else
	trap 'tput sgr0; tput cnorm; tput cup ${ROWS} 0 ; print "$COUNTER  \c"; exit' 0 1 2 3 9 15
	fi
else
trap 'tput clear; tput sgr0; tput cnorm; exit' 0 1 2 3 9 15
fi


trap 'ReSize' WINCH

ReSize()
{
	print "${CLRSCRN}\c"
	COUNTER=$PATTSIZE
	COLS=`tput cols`
	ROWS=`tput lines`
	let ROWS=${ROWS}-1
	let COL2=${COLS}/2
	let ROW=${ROWS}/2
	COL=1
}

if [ -n "$NOCLEAR" ]
then
	CLRSCRN=""
else
	CLRSCRN=`tput clear`
fi

OUTCHAR=#

ReSize

tput civis

while true
do
	print "${CLRSCRN}\c"
	COUNTER=$PATTSIZE
	let ROW=${ROWS}/2
	COL=1
	until [ $COUNTER -eq 0 ]
	do
		let DIRECTION=${RANDOM}%10

		case $DIRECTION in
		0)
			print "${RINGBELL}${UNFLASH}\c"
			OUTCHAR=#
			;;
		1)
			let ROW=${ROW}+1
			let COL=${COL}-1
			;;
		2)
			let ROW=${ROW}+1
			;;
		3)
			let ROW=${ROW}+1
			let COL=${COL}+1
			;;
		4)
			let COL=${COL}-1
			;;
		5)
			print "${RINGBELL}${FLASH}\c"
			OUTCHAR=$ALTCHAR
			;;
		6)
			let COL=${COL}+1
			;;
		7)
			let ROW=${ROW}-1
			let COL=${COL}-1
			;;
		8)
			let ROW=${ROW}-1
			;;
		9)
			let ROW=${ROW}-1
			let COL=${COL}+1
			;;
		esac

		if [ ${ROW} -gt ${ROWS} ]
		then
			ROW=$ROWS
		fi

		if [ ${ROW} -lt 1 ]
		then
			ROW=1
		fi

		if [ ${COL} -gt ${COL2} ]
		then
			COL=$COL2
		fi

		if [ ${COL} -lt 1 ]
		then
			COL=1
		fi

		let LCOL=${COL2}+1-${COL}
		let RCOL=${COL2}+${COL}
		RorOut $ROW $LCOL $RCOL "$OUTCHAR"
		let COUNTER=${COUNTER}-1
			
	done
	if [ -z "$LOOP" ]
	then
		exit 0
	else
		tput home
		if [ $SLEEPTIME -eq 0 ]
		then
			read NADA
		else
			sleep $SLEEPTIME
		fi
	fi
done
##############################################################################
#	EOF cror
##############################################################################
