#!/bin/ksh
############################################################################## 
#	UNIX SHELL SCRIPT
#	NAME		TITLE
#	eightball	the magic eight ball prognosticator
#
#	SYNOPSIS
#	
#	DESCRIPTION
#
#	RETURN VALUE
#	none meaningful
#	
#	NOTES / CAVEATS
#	For entertainment purposes only; actual dependence on eightball
#	prognostications may lead to the consequences such behavior
#	deserves!
#		
#	AUTHOR, REVIEWER
#
#	MODIFICATIONS
#	Tue Nov  8 13:04:32 MST 2016 - Leif Fellague
#	The default behavior is to populate the PREDICT list with the standard
#	20 answers from the Magic Eight Ball toy (per Wikipedia).  While this
#	more accurately emulates the MEB's behavior, the MEB has a strong
#	positive bias, with 10 affirmative answers, 5 negative, and 5
#	non-committal.  If any command line argument is provided (in future
#	this might be limited to a specific flag), the script will add 5
#	negative and 5 non-committal responses to the "classic" answer set in
#	order to balance the answer pool.
#		
##############################################################################

BIAS="classic"
if [ "${1:-}" ]
then
	BIAS="neutral"
fi

ScrollOff()
{
	sleep 0.5
	SCRLINES=$(tput lines)
	EIGHT=8
	for x in {1..${SCRLINES}}
	do
		sleep 0.05
		echo $EIGHTS
		EIGHTS=${EIGHTS}8
	done
	tput clear
}

#
# Uncredited design from the Sports & outdoors -> Billiards
#  archive at: www.asciiart.eu
#

EIGHTBALL1="
        ____
    ,dP9CGG88@b,
  ,IP  _   Y888@@b,
 dIi  (_)   G8888@b
dCII  (_)   G8888@@b
GCCIi     ,GG8888@@@
GGCCCCCCCGGG88888@@@
GGGGCCCGGGG88888@@@@..."

EIGHTBALL2="\
Y8GGGGGG8888888@@@@P.....
 Y88888888888@@@@@P......
 \`Y8888888@@@@@@@P'......
    \`@@@@@@@@@P'.......
        \"\"\"\"........"

CLS=$(tput clear)

set -A PREDICT \
"Outlook not so good" \
"As I see it, yes" \
"Without a doubt" \
"It is certain" \
"Cannot predict now" \
"Concentrate and ask again" \
"Better not tell you now" \
"Don't count on it" \
"Signs point to yes" \
"Outlook good" \
"It is decidedly so" \
"My reply is no" \
"Reply hazy try again" \
"Very doubtful" \
"You may rely on it" \
"My sources say no" \
"Ask again later" \
"Yes, definitely" \
"Yes" \
"Most likely"

if [ "$BIAS" = neutral ]
then
set -A PREDICT \
"${PREDICT[@]}" \
"The portents are unclear" \
"That's a big NEGATORY, junior" \
"Perhaps" \
"It appears unlikely" \
"Could be" \
"No" \
"Oh, does it really matter?  Maybe I'll tell you if you ask again..." \
"No way" \
"Whatever..." \
"The omens do not favor it"
fi

print "${CLS}
${EIGHTBALL1}      Welcome to the ${BIAS} Magic Eight Ball.
${EIGHTBALL2}
Ask me a question, and I will give you a yes or no answer.
Probably . . ."


while read QUEST?'
Ask your question: '
do
	if [ -z "$QUEST" ]
	then
		#echo "Answer:   So long, sucker!"
		print "${CLS}
${EIGHTBALL1}      Well, if there are no more questions, I'll be on my way . . .
${EIGHTBALL2}"
		ScrollOff
		exit 0
	fi
	print "${CLS}\n\n\nOh Magic Eightball: ${QUEST}"
	print "${EIGHTBALL1}     ${PREDICT[RANDOM%${#PREDICT[*]}]}"
	print "${EIGHTBALL2}"
done


##############################################################################
#	EOF eightball
##############################################################################
