#!/usr/bin/python
# Hangman Game
#
# The classic game of Hangman. The computer picks a random word
# and the player tries to guess it, one letter at a time. If the player
# can't guess the word in time, the little stick figure gets hanged.
#
# Michael Dawson

# imports
import random
import string
from sys import argv

cmdargs = ( argv )
if len(argv) > 1 :
    minsize = int(cmdargs[1])
else :
    minsize = 5

#constants
PERFECT = r"""
 _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_
  //\    //\    //\    //\    //\    //\    //\    //\    //\


    //   ) )                  //  ) )                        //
   //___/ /  ___      __   __//__  ___      ___    __  ___  //
  / ____ / //___) ) //  ) ) //   //___) ) //   ) )  / /    //
 //       //       //      //   //       //        / /
//       ((____   //      //   ((____   ((____    / /    //



 _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_
  //\    //\    //\    //\    //\    //\    //\    //\    //\
"""

HANGMAN = (
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /       //\\ 
| |/       //  \\ 
| |       //    \\ 
| |       \\ __ // 
| |        ` -- ' 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |           `-' 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
| | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |         \ . . / 
| |          |   | 
| |          | . | 
| |          |   | 
| |           \_/ 
| | 
| | 
| | 
| | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . / 
| |       // |   | 
| |      //  | . | 
| |     ')   |   | 
| |           \_/ 
| | 
| | 
| | 
| | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . Y\ 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |           \_/ 
| | 
| | 
| | 
| | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        / / \ \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . Y\ 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |          ||^-  
| |          || 
| |          || 
| |          || 
| |         / | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        ||.-''. 
| |/         |/  _  \        ____    ___   ____ 
| |          ||  `/,|       |  _ \  |_ _| |  _ \ 
| |          (\\`_.'        | |_) |  | |  | |_) | 
| |         .-`--'.         |  _ < _ | | _|  __/ 
| |        /Y . . Y\        |_| \_(_)___(_)_| (_) 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |          ||^|| 
| |          || || 
| |          || || 
| |          || || 
| |         / | | \ 
^^^^^^^^^^|_`-' `-' |^^^| 
|^|^^^^^^^\ \       '^|^| 
| |        \ \        | | 
: :         \ \       : : 
. .          `'       . .
""") 


SAVEMAN = r"""
             .'''.         __        ___                   _  
            /  _  \        \ \      / / |__   _____      _| |
            | `\' |         \ \ /\ / /| '_ \ / _ \ \ /\ / / |
             \`-'/           \ V  V / | | | |  __/\ V  V /|_|
            .-`--'.           \_/\_/  |_| |_|\___| \_/\_/ (_)
           /Y . . Y\        _____ _                 _
          // |   | \\      |_   _| |__   __ _ _ __ | | _____
         //  | . |  \\       | | | '_ \ / _` | '_ \| |/ / __|
        ')   |   |   (`      | | | | | | (_| | | | |   <\__ \_
             ||^||           |_| |_| |_|\__,_|_| |_|_|\_\___( )
             || ||                                          |/
             || ||          ____       _ _
             || ||         |  _ \ __ _| | |
            / | | \        | |_) / _` | | |
^^^^^^^^^^^^^^^^^^^^^^^^|  |  __/ (_| | |_|
|^|^^^^^^^^^^^^^^^^^^^|^|  |_|   \__,_|_(_)
| |                   | | 
: :                   : : 
. .                   . . 
"""


MAX_WRONG = len(HANGMAN) - 1

WORDS = [ "abandon", "ability", "abortion", "about", "above", "abroad", "absence",
"absolute", "absolutely", "absorb", "abstract", "abuse", "academic",
"accelerate", "accent", "accept", "acceptable", "acceptance", "access",
"accessible", "accident", "accommodate", "accompany", "accomplish",
"accomplishment", "according", "account", "accountability", "accounting",
"accuracy", "accurate", "accurately", "accusation", "accuse", "achieve",
"achievement", "acknowledge", "acquire", "acquisition", "across", "action",
"active", "actively", "activist", "activity", "actor", "actress", "actual",
"actually", "adapt", "added", "addition", "additional", "address", "adequate",
"adjust", "adjustment", "administer", "administration", "administrative",
"administrator", "admire", "admission", "admit", "adolescent", "adopt",
"adoption", "adult", "advance", "advanced", "advantage", "adventure",
"advertising", "advice", "advise", "adviser", "advocate", "aesthetic",
"affair", "affect", "afford", "afraid", "african", "after", "afternoon",
"afterward", "again", "against", "agency", "agenda", "agent", "aggression",
"aggressive", "agree", "agreement", "agricultural", "agriculture", "ahead",
"aircraft", "airline", "airplane", "airport", "aisle", "alarm", "album",
"alcohol", "alien", "alike", "alive", "allegation", "alleged", "allegedly",
"alley", "alliance", "allow", "almost", "alone", "along", "alongside",
"already", "alter", "alternative", "although", "altogether", "aluminum",
"always", "amazing", "ambassador", "ambition", "ambitious", "amendment",
"american", "among", "amount", "analysis", "analyst", "analyze", "ancestor",
"ancient", "angel", "anger", "angle", "angry", "animal", "ankle",
"anniversary", "announce", "announcement", "annual", "annually", "anonymous",
"another", "answer", "anticipate", "anxiety", "anxious", "anybody", "anymore",
"anyone", "anything", "anyway", "anywhere", "apart", "apartment", "apologize",
"apology", "apparent", "apparently", "appeal", "appear", "appearance", "apple",
"application", "apply", "appoint", "appointment", "appreciate", "appreciation",
"approach", "appropriate", "approval", "approve", "approximately", "architect",
"architecture", "arena", "argue", "argument", "arise", "armed", "around",
"arrange", "arrangement", "array", "arrest", "arrival", "arrive", "arrow",
"article", "articulate", "artifact", "artificial", "artist", "artistic",
"asian", "aside", "asleep", "aspect", "assault", "assemble", "assembly",
"assert", "assess", "assessment", "asset", "assign", "assignment", "assist",
"assistance", "assistant", "associate", "associated", "association", "assume",
"assumption", "assure", "astronomer", "athlete", "athletic", "atmosphere",
"attach", "attack", "attempt", "attend", "attendance", "attention", "attitude",
"attorney", "attract", "attraction", "attractive", "attribute", "auction",
"audience", "author", "authority", "authorize", "automatic", "automatically",
"automobile", "autonomy", "availability", "available", "average", "avoid",
"await", "awake", "award", "aware", "awareness", "awful", "background",
"backyard", "bacteria", "badly", "balance", "balanced", "balloon", "ballot",
"banana", "banker", "banking", "barely", "barrel", "barrier", "baseball",
"basement", "basic", "basically", "basis", "basket", "basketball", "bathroom",
"battery", "battle", "beach", "beard", "beast", "beautiful", "beauty",
"because", "become", "bedroom", "before", "begin", "beginning", "behalf",
"behave", "behavior", "behavioral", "behind", "being", "belief", "believe",
"belly", "belong", "below", "bench", "beneath", "benefit", "beside", "besides",
"better", "between", "beyond", "bible", "bicycle", "billion", "biography",
"biological", "biology", "birth", "birthday", "bishop", "bitter", "black",
"blade", "blame", "blank", "blanket", "blast", "blend", "bless", "blessing",
"blind", "blink", "block", "blond", "blood", "bloody", "board", "boast",
"bombing", "bonus", "boost", "booth", "border", "boring", "borrow", "bother",
"bottle", "bottom", "bounce", "boundary", "boyfriend", "brain", "brake",
"branch", "brand", "brave", "bread", "break", "breakfast", "breast", "breath",
"breathe", "breathing", "breeze", "brick", "bride", "bridge", "brief",
"briefly", "bright", "brilliant", "bring", "british", "broad", "broadcast",
"broken", "broker", "bronze", "brother", "brown", "brush", "brutal", "bubble",
"bucket", "buddy", "budget", "build", "builder", "building", "bullet", "bunch",
"burden", "bureau", "burning", "burst", "business", "businessman", "butter",
"butterfly", "button", "buyer", "cabin", "cabinet", "cable", "calculate",
"calculation", "calendar", "camera", "campaign", "campus", "canadian",
"cancel", "cancer", "candidate", "candle", "candy", "canvas", "capability",
"capable", "capacity", "capital", "captain", "capture", "carbohydrate",
"carbon", "career", "careful", "carefully", "cargo", "carpet", "carrier",
"carrot", "carry", "cartoon", "carve", "casino", "casual", "casualty",
"catalog", "catch", "category", "catholic", "cattle", "cause", "cease",
"ceiling", "celebrate", "celebration", "celebrity", "cemetery", "center",
"central", "century", "ceremony", "certain", "certainly", "chain", "chair",
"chairman", "challenge", "chamber", "champion", "championship", "chance",
"change", "changing", "channel", "chaos", "chapter", "character",
"characteristic", "characterize", "charge", "charity", "charm", "chart",
"charter", "chase", "cheap", "cheat", "check", "cheek", "cheer", "cheese",
"chemical", "chemistry", "chest", "chicken", "chief", "child", "childhood",
"chill", "chinese", "chocolate", "choice", "cholesterol", "choose",
"christian", "christianity", "christmas", "chronic", "chunk", "church",
"cigarette", "circle", "circuit", "circumstance", "citizen", "citizenship",
"civic", "civil", "civilian", "civilization", "claim", "class", "classic",
"classical", "classify", "classroom", "clean", "clear", "clearly", "clerk",
"click", "client", "cliff", "climate", "climb", "cling", "clinic", "clinical",
"clock", "close", "closed", "closely", "closer", "closest", "closet", "cloth",
"clothes", "clothing", "cloud", "cluster", "coach", "coalition", "coast",
"coastal", "cocaine", "coffee", "cognitive", "collaboration", "collapse",
"collar", "colleague", "collect", "collection", "collective", "collector",
"college", "colonial", "colony", "color", "colorful", "column", "columnist",
"combat", "combination", "combine", "combined", "comedy", "comfort",
"comfortable", "coming", "command", "commander", "comment", "commercial",
"commission", "commissioner", "commit", "commitment", "committee", "commodity",
"common", "commonly", "communicate", "communication", "community", "companion",
"company", "comparable", "compare", "comparison", "compel", "compelling",
"compensation", "compete", "competition", "competitive", "competitor",
"complain", "complaint", "complete", "completely", "complex", "complexity",
"compliance", "complicated", "comply", "component", "compose", "composition",
"compound", "comprehensive", "comprise", "compromise", "computer", "concede",
"conceive", "concentrate", "concentration", "concept", "conception", "concern",
"concerned", "concerning", "concert", "conclude", "conclusion", "concrete",
"condemn", "condition", "conduct", "conference", "confess", "confession",
"confidence", "confident", "confirm", "conflict", "confront", "confrontation",
"confuse", "confusion", "congress", "congressional", "connect", "connection",
"conscience", "conscious", "consciousness", "consecutive", "consensus",
"consent", "consequence", "consequently", "conservation", "conservative",
"consider", "considerable", "considerably", "consideration", "consist",
"consistent", "consistently", "conspiracy", "constant", "constantly",
"constitute", "constitution", "constitutional", "constraint", "construct",
"construction", "consult", "consultant", "consume", "consumer", "consumption",
"contact", "contain", "container", "contemplate", "contemporary", "contend",
"content", "contest", "context", "continent", "continue", "continued",
"continuing", "continuous", "contract", "contractor", "contrast", "contribute",
"contribution", "contributor", "control", "controversial", "controversy",
"convenience", "convention", "conventional", "conversation", "conversion",
"convert", "convey", "convict", "conviction", "convince", "convinced",
"cookie", "cooking", "cooperate", "cooperation", "cooperative", "coordinate",
"coordinator", "corner", "corporate", "corporation", "correct", "correctly",
"correlation", "correspondent", "corridor", "corruption", "costly", "costume",
"cottage", "cotton", "couch", "could", "council", "counsel", "counseling",
"counselor", "count", "counter", "counterpart", "country", "county", "couple",
"courage", "course", "court", "courtroom", "cousin", "cover", "coverage",
"crack", "craft", "crash", "crawl", "crazy", "cream", "create", "creation",
"creative", "creativity", "creature", "credibility", "credit", "crime",
"criminal", "crisis", "criteria", "critic", "critical", "criticism",
"criticize", "cross", "crowd", "crowded", "crucial", "cruel", "cruise",
"crush", "crystal", "cuban", "cultural", "culture", "curiosity", "curious",
"currency", "current", "currently", "curriculum", "curtain", "curve",
"custody", "custom", "customer", "cycle", "daily", "damage", "dance", "dancer",
"dancing", "danger", "dangerous", "darkness", "database", "daughter",
"deadline", "deadly", "dealer", "death", "debate", "debris", "debut", "decade",
"decent", "decide", "decision", "declare", "decline", "decorate", "decrease",
"dedicate", "deeply", "defeat", "defend", "defendant", "defender", "defense",
"defensive", "deficit", "define", "definitely", "definition", "degree",
"delay", "deliberately", "delicate", "delight", "deliver", "delivery",
"demand", "democracy", "democrat", "democratic", "demographic", "demonstrate",
"demonstration", "denial", "dense", "density", "depart", "department",
"departure", "depend", "dependent", "depending", "depict", "deploy", "deposit",
"depressed", "depression", "depth", "deputy", "derive", "descend", "describe",
"description", "desert", "deserve", "design", "designer", "desire",
"desperate", "desperately", "despite", "dessert", "destination", "destroy",
"destruction", "detail", "detailed", "detect", "detective", "determination",
"determine", "devastating", "develop", "developer", "developing",
"development", "developmental", "device", "devil", "devote", "diabetes",
"diagnose", "diagnosis", "dialogue", "diamond", "diary", "dictate", "differ",
"difference", "different", "differently", "difficult", "difficulty", "digital",
"dignity", "dilemma", "dimension", "diminish", "dining", "dinner", "diplomat",
"diplomatic", "direct", "direction", "directly", "director", "dirty",
"disability", "disabled", "disagree", "disappear", "disappointed",
"disappointment", "disaster", "discipline", "disclose", "discount",
"discourage", "discourse", "discover", "discovery", "discrimination",
"discuss", "discussion", "disease", "dismiss", "disorder", "display",
"dispute", "dissolve", "distance", "distant", "distinct", "distinction",
"distinctive", "distinguish", "distract", "distribute", "distribution",
"district", "disturb", "disturbing", "diverse", "diversity", "divide",
"divine", "division", "divorce", "doctor", "doctrine", "document",
"documentary", "domain", "domestic", "dominant", "dominate", "donate",
"donation", "donor", "doorway", "double", "doubt", "dough", "downtown",
"dozen", "draft", "drain", "drama", "dramatic", "dramatically", "drawer",
"drawing", "dream", "dress", "dried", "drift", "drill", "drink", "drinking",
"drive", "driver", "driveway", "driving", "drown", "drunk", "during", "dutch",
"dying", "dynamic", "dynamics", "eager", "early", "earnings", "earth",
"earthquake", "easily", "eastern", "eating", "ecological", "economic",
"economically", "economics", "economist", "economy", "ecosystem", "edition",
"editor", "educate", "education", "educational", "educator", "effect",
"effective", "effectively", "effectiveness", "efficiency", "efficient",
"effort", "eight", "eighth", "either", "elaborate", "elbow", "elder",
"elderly", "elect", "election", "electric", "electrical", "electricity",
"electronic", "electronics", "elegant", "element", "elementary", "elephant",
"elevator", "eleven", "eligible", "eliminate", "elite", "elsewhere",
"embarrassed", "embrace", "emerge", "emergency", "emerging", "emission",
"emotion", "emotional", "emotionally", "emphasis", "emphasize", "empire",
"employ", "employee", "employer", "employment", "empty", "enable", "enact",
"encounter", "encourage", "encouraging", "endless", "endorse", "endure",
"enemy", "energy", "enforce", "enforcement", "engage", "engagement", "engine",
"engineer", "engineering", "english", "enhance", "enjoy", "enormous", "enough",
"enroll", "ensure", "enter", "enterprise", "entertainment", "enthusiasm",
"entire", "entirely", "entitle", "entity", "entrance", "entrepreneur", "entry",
"envelope", "environment", "environmental", "envision", "epidemic", "episode",
"equal", "equality", "equally", "equation", "equip", "equipment", "equity",
"equivalent", "error", "escape", "especially", "essay", "essence", "essential",
"essentially", "establish", "establishment", "estate", "estimate", "estimated",
"ethical", "ethics", "ethnic", "european", "evaluate", "evaluation", "evening",
"event", "eventually", "every", "everybody", "everyday", "everyone",
"everything", "everywhere", "evidence", "evident", "evolution", "evolve",
"exact", "exactly", "examination", "examine", "example", "exceed", "excellent",
"except", "exception", "excessive", "exchange", "excited", "excitement",
"exciting", "exclude", "exclusive", "exclusively", "excuse", "execute",
"execution", "executive", "exercise", "exhaust", "exhibit", "exhibition",
"exist", "existence", "existing", "exotic", "expand", "expansion", "expect",
"expectation", "expected", "expedition", "expense", "expensive", "experience",
"experienced", "experiment", "experimental", "expert", "expertise", "explain",
"explanation", "explicit", "explode", "exploit", "exploration", "explore",
"explosion", "export", "expose", "exposure", "express", "expression", "extend",
"extended", "extension", "extensive", "extent", "external", "extra",
"extraordinary", "extreme", "extremely", "eyebrow", "fabric", "facilitate",
"facility", "factor", "factory", "faculty", "failure", "faint", "fairly",
"faith", "false", "familiar", "family", "famous", "fantastic", "fantasy",
"farmer", "fascinating", "fashion", "faster", "fatal", "father", "fatigue",
"fault", "favor", "favorable", "favorite", "feather", "feature", "federal",
"feedback", "feeling", "fellow", "female", "feminist", "fence", "festival",
"fever", "fewer", "fiber", "fiction", "field", "fierce", "fifteen", "fifth",
"fifty", "fight", "fighter", "fighting", "figure", "filter", "final",
"finally", "finance", "financial", "finding", "finger", "finish", "firmly",
"first", "fiscal", "fisherman", "fishing", "fitness", "fixed", "flame",
"flash", "flavor", "fleet", "flesh", "flexibility", "flexible", "flight",
"float", "flood", "floor", "flour", "flower", "fluid", "flying", "focus",
"follow", "following", "football", "forbid", "force", "forehead", "foreign",
"foreigner", "forest", "forever", "forget", "forgive", "formal", "format",
"formation", "former", "formerly", "formula", "forth", "fortunately",
"fortune", "forty", "forum", "forward", "foster", "found", "foundation",
"founder", "fourth", "fraction", "fragile", "fragment", "frame", "framework",
"franchise", "frankly", "fraud", "freedom", "freely", "freeze", "french",
"frequency", "frequent", "frequently", "fresh", "freshman", "friend",
"friendly", "friendship", "front", "frontier", "frown", "frozen", "fruit",
"frustrate", "frustration", "fulltime", "fully", "function", "functional",
"fundamental", "funding", "funeral", "funny", "furniture", "furthermore",
"future", "galaxy", "gallery", "garage", "garbage", "garden", "garlic",
"gasoline", "gather", "gathering", "gender", "general", "generally",
"generate", "generation", "generous", "genetic", "genius", "genre", "gentle",
"gentleman", "gently", "genuine", "german", "gesture", "ghost", "giant",
"gifted", "girlfriend", "given", "glance", "glass", "glimpse", "global",
"globe", "glory", "glove", "golden", "govern", "government", "governor",
"grace", "grade", "gradually", "graduate", "graduation", "grain", "grand",
"grandchild", "grandfather", "grandmother", "grandparent", "grant", "grape",
"grasp", "grass", "grateful", "grave", "gravity", "great", "greatest",
"greatly", "greek", "green", "greet", "grief", "grocery", "gross", "ground",
"group", "growing", "growth", "guarantee", "guard", "guess", "guest",
"guidance", "guide", "guideline", "guilt", "guilty", "guitar", "habit",
"habitat", "halfway", "hallway", "handful", "handle", "handsome", "happen",
"happily", "happiness", "happy", "harassment", "hardly", "hardware", "harmony",
"harsh", "harvest", "hazard", "headache", "headline", "headquarters", "health",
"healthcare", "healthy", "hearing", "heart", "heaven", "heavily", "heavy",
"height", "helicopter", "hello", "helmet", "helpful", "hence", "heritage",
"herself", "hesitate", "hidden", "highlight", "highly", "highway", "himself",
"hispanic", "historian", "historic", "historical", "historically", "history",
"hockey", "holiday", "homeland", "homeless", "homework", "honest", "honestly",
"honey", "honor", "hopefully", "horizon", "hormone", "horrible", "horror",
"horse", "hospital", "hostage", "hostile", "hotel", "house", "household",
"housing", "however", "human", "humanity", "humor", "hundred", "hunger",
"hungry", "hunter", "hunting", "hurricane", "hurry", "husband", "hypothesis",
"ideal", "identical", "identification", "identify", "identity", "ideological",
"ideology", "ignore", "illegal", "illness", "illusion", "illustrate", "image",
"imagination", "imagine", "immediate", "immediately", "immigrant",
"immigration", "immune", "impact", "implement", "implementation",
"implication", "imply", "import", "importance", "important", "importantly",
"impose", "impossible", "impress", "impression", "impressive", "improve",
"improved", "improvement", "impulse", "incentive", "incident", "include",
"including", "income", "incorporate", "increase", "increased", "increasing",
"increasingly", "incredible", "incredibly", "indeed", "independence",
"independent", "index", "indian", "indicate", "indication", "indicator",
"indigenous", "individual", "industrial", "industry", "inevitable",
"inevitably", "infant", "infection", "inflation", "influence", "influential",
"inform", "informal", "information", "infrastructure", "ingredient",
"inherent", "inherit", "initial", "initially", "initiate", "initiative",
"injure", "injury", "inmate", "inner", "innocent", "innovation", "innovative",
"input", "inquiry", "insect", "insert", "inside", "insight", "insist",
"inspection", "inspector", "inspiration", "inspire", "install", "installation",
"instance", "instant", "instantly", "instead", "instinct", "institution",
"institutional", "instruct", "instruction", "instructional", "instructor",
"instrument", "insurance", "intact", "integrate", "integrated", "integration",
"integrity", "intellectual", "intelligence", "intelligent", "intend",
"intense", "intensity", "intent", "intention", "interact", "interaction",
"interest", "interested", "interesting", "interfere", "interior", "internal",
"international", "internet", "interpret", "interpretation", "interrupt",
"interval", "intervention", "interview", "intimate", "introduce",
"introduction", "invade", "invasion", "invent", "invention", "inventory",
"invest", "investigate", "investigation", "investigator", "investment",
"investor", "invisible", "invitation", "invite", "involve", "involved",
"involvement", "iraqi", "irish", "ironically", "irony", "islam", "islamic",
"island", "isolate", "isolated", "isolation", "israeli", "issue", "italian",
"itself", "jacket", "japanese", "jeans", "jewelry", "jewish", "joint",
"journal", "journalism", "journalist", "journey", "judge", "judgment",
"judicial", "juice", "jungle", "junior", "jurisdiction", "juror", "justice",
"justify", "killer", "killing", "kingdom", "kitchen", "kneel", "knife",
"knock", "knowledge", "known", "korean", "label", "labor", "laboratory",
"ladder", "landing", "landmark", "landscape", "language", "large", "largely",
"laser", "lately", "later", "latin", "latter", "laugh", "laughter", "launch",
"laundry", "lawmaker", "lawsuit", "lawyer", "layer", "leader", "leadership",
"leading", "league", "learn", "learning", "least", "leather", "leave",
"lecture", "legacy", "legal", "legally", "legend", "legislation",
"legislative", "legislator", "legislature", "legitimate", "lemon", "length",
"lesson", "letter", "level", "liability", "liberal", "liberty", "library",
"license", "lifestyle", "lifetime", "light", "lighting", "lightly",
"lightning", "likelihood", "likely", "likewise", "limit", "limitation",
"limited", "liquid", "listen", "listener", "literally", "literary",
"literature", "little", "liver", "living", "lobby", "local", "locate",
"location", "logic", "logical", "lonely", "longtime", "loose", "lovely",
"lover", "lower", "loyal", "loyalty", "lucky", "lunch", "machine", "magazine",
"magic", "magnetic", "magnitude", "mainly", "mainstream", "maintain",
"maintenance", "major", "majority", "maker", "makeup", "manage", "management",
"manager", "managing", "mandate", "manipulate", "manner", "mansion", "manual",
"manufacturer", "manufacturing", "marble", "march", "margin", "marine",
"marker", "market", "marketing", "marketplace", "marriage", "married", "marry",
"massive", "master", "match", "material", "mathematics", "matter", "maximum",
"maybe", "mayor", "meaning", "meaningful", "meantime", "meanwhile", "measure",
"measurement", "mechanic", "mechanical", "mechanism", "medal", "media",
"medical", "medication", "medicine", "medium", "meeting", "member",
"membership", "memory", "mental", "mentally", "mention", "mentor", "merchant",
"merely", "merit", "message", "metal", "metaphor", "meter", "method",
"metropolitan", "mexican", "middle", "midnight", "midst", "might", "migration",
"military", "million", "mineral", "minimal", "minimize", "minimum", "minister",
"ministry", "minor", "minority", "minute", "miracle", "mirror", "missile",
"missing", "mission", "missionary", "mistake", "mixed", "mixture", "mobile",
"model", "moderate", "modern", "modest", "modify", "molecule", "moment",
"momentum", "money", "monitor", "monkey", "monster", "month", "monthly",
"monument", "moral", "moreover", "morning", "mortality", "mortgage", "mostly",
"mother", "motion", "motivate", "motivation", "motive", "motor", "mount",
"mountain", "mouse", "mouth", "movement", "movie", "multiple", "municipal",
"murder", "muscle", "museum", "mushroom", "music", "musical", "musician",
"muslim", "mutter", "mutual", "myself", "mysterious", "mystery", "naked",
"narrative", "narrow", "nasty", "nation", "national", "nationwide", "native",
"natural", "naturally", "nature", "naval", "nearby", "nearly", "necessarily",
"necessary", "necessity", "needle", "negative", "negotiate", "negotiation",
"neighbor", "neighborhood", "neighboring", "neither", "nerve", "nervous",
"network", "neutral", "never", "nevertheless", "newly", "newspaper", "night",
"nightmare", "nobody", "noise", "nomination", "nominee", "nonetheless",
"nonprofit", "normal", "normally", "north", "northeast", "northern",
"northwest", "notebook", "nothing", "notice", "notion", "novel", "nowhere",
"nuclear", "number", "numerous", "nurse", "nutrient", "object", "objection",
"objective", "obligation", "observation", "observe", "observer", "obstacle",
"obtain", "obvious", "obviously", "occasion", "occasional", "occasionally",
"occupation", "occupy", "occur", "ocean", "offender", "offense", "offensive",
"offer", "offering", "office", "officer", "official", "officially", "often",
"olympic", "olympics", "ongoing", "onion", "online", "opening", "openly",
"opera", "operate", "operating", "operation", "operator", "opinion",
"opponent", "opportunity", "oppose", "opposed", "opposite", "opposition",
"optimistic", "option", "orange", "orbit", "order", "ordinary", "organ",
"organic", "organism", "organization", "organizational", "organize",
"organized", "orientation", "origin", "original", "originally", "other",
"others", "otherwise", "ought", "ourselves", "outcome", "outdoor", "outer",
"outfit", "outlet", "outline", "output", "outside", "outsider", "outstanding",
"overall", "overcome", "overlook", "overnight", "oversee", "overwhelm",
"overwhelming", "owner", "ownership", "oxygen", "package", "painful", "paint",
"painter", "painting", "palace", "palestinian", "panel", "panic", "paper",
"parade", "parent", "parental", "parish", "parking", "partial", "partially",
"participant", "participate", "participation", "particle", "particular",
"particularly", "partly", "partner", "partnership", "party", "passage",
"passenger", "passing", "passion", "pasta", "pastor", "patch", "patent",
"patience", "patient", "patrol", "patron", "pattern", "pause", "payment",
"peace", "peaceful", "peanut", "peasant", "penalty", "pencil", "pension",
"people", "pepper", "perceive", "perceived", "percentage", "perception",
"perfect", "perfectly", "perform", "performance", "performer", "perhaps",
"period", "permanent", "permission", "permit", "persian", "persist", "person",
"personal", "personality", "personally", "personnel", "perspective",
"persuade", "phase", "phenomenon", "philosophical", "philosophy", "phone",
"photo", "photograph", "photographer", "photography", "phrase", "physical",
"physically", "physician", "physics", "piano", "pickup", "picture", "piece",
"pillow", "pilot", "pioneer", "pistol", "pitch", "pitcher", "pizza", "place",
"placement", "plain", "plaintiff", "plane", "planet", "planner", "planning",
"plant", "plastic", "plate", "platform", "player", "playoff", "plead",
"pleasant", "please", "pleased", "pleasure", "plenty", "plunge", "pocket",
"poetry", "point", "police", "policeman", "policy", "political", "politically",
"politician", "politics", "pollution", "popular", "popularity", "population",
"porch", "portfolio", "portion", "portrait", "portray", "position", "positive",
"possess", "possession", "possibility", "possible", "possibly", "poster",
"potato", "potential", "potentially", "pound", "poverty", "powder", "power",
"powerful", "practical", "practically", "practice", "practitioner", "praise",
"prayer", "preach", "precious", "precise", "precisely", "predator", "predict",
"prediction", "prefer", "preference", "pregnancy", "pregnant", "preliminary",
"premise", "premium", "preparation", "prepare", "prescription", "presence",
"present", "presentation", "preserve", "presidency", "president",
"presidential", "press", "pressure", "presumably", "pretend", "pretty",
"prevail", "prevent", "prevention", "previous", "previously", "price", "pride",
"priest", "primarily", "primary", "prime", "principal", "principle", "print",
"prior", "priority", "prison", "prisoner", "privacy", "private", "privately",
"privilege", "prize", "probably", "problem", "procedure", "proceed", "process",
"processing", "processor", "proclaim", "produce", "producer", "product",
"production", "productive", "productivity", "profession", "professional",
"professor", "profile", "profit", "profound", "program", "programming",
"progress", "progressive", "prohibit", "project", "projection", "prominent",
"promise", "promising", "promote", "promotion", "prompt", "proof", "proper",
"properly", "property", "proportion", "proposal", "propose", "proposed",
"prosecution", "prosecutor", "prospect", "protect", "protection", "protective",
"protein", "protest", "protocol", "proud", "prove", "provide", "provided",
"provider", "province", "provision", "provoke", "psychological",
"psychologist", "psychology", "public", "publication", "publicity", "publicly",
"publish", "publisher", "pulse", "punch", "punish", "punishment", "purchase",
"purple", "purpose", "purse", "pursue", "pursuit", "puzzle", "qualify",
"quality", "quantity", "quarter", "quarterback", "queen", "quest", "question",
"questionnaire", "quick", "quickly", "quiet", "quietly", "quite", "quote",
"rabbit", "racial", "racism", "radar", "radiation", "radical", "radio",
"railroad", "raise", "rally", "ranch", "random", "range", "rapid", "rapidly",
"rarely", "rather", "rating", "ratio", "rational", "reach", "react",
"reaction", "reader", "readily", "reading", "ready", "realistic", "reality",
"realize", "really", "realm", "reason", "reasonable", "rebel", "rebuild",
"recall", "receive", "receiver", "recent", "recently", "reception",
"recession", "recipe", "recipient", "recognition", "recognize", "recommend",
"recommendation", "record", "recording", "recover", "recovery", "recruit",
"reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform",
"refrigerator", "refuge", "refugee", "refuse", "regain", "regard", "regarding",
"regardless", "regime", "region", "regional", "register", "regret", "regular",
"regularly", "regulate", "regulation", "regulator", "regulatory",
"rehabilitation", "reinforce", "reject", "relate", "related", "relation",
"relationship", "relative", "relatively", "relax", "release", "relevant",
"reliability", "reliable", "relief", "relieve", "religion", "religious",
"reluctant", "remain", "remaining", "remark", "remarkable", "remember",
"remind", "reminder", "remote", "removal", "remove", "render", "rental",
"repair", "repeat", "repeatedly", "replace", "replacement", "reply", "report",
"reportedly", "reporter", "reporting", "represent", "representation",
"representative", "republic", "republican", "reputation", "request", "require",
"required", "requirement", "rescue", "research", "researcher", "resemble",
"reservation", "reserve", "residence", "resident", "residential", "resign",
"resist", "resistance", "resolution", "resolve", "resort", "resource",
"respect", "respectively", "respond", "respondent", "response",
"responsibility", "responsible", "restaurant", "restore", "restrict",
"restriction", "result", "resume", "retail", "retailer", "retain", "retire",
"retired", "retirement", "retreat", "return", "reveal", "revelation",
"revenue", "reverse", "review", "revolution", "revolutionary", "reward",
"rhetoric", "rhythm", "ribbon", "rider", "ridge", "ridiculous", "rifle",
"right", "risky", "ritual", "rival", "river", "robot", "rocket", "rolling",
"roman", "romance", "romantic", "rough", "roughly", "round", "route",
"routine", "routinely", "royal", "rubber", "ruling", "rumor", "runner",
"running", "rural", "russian", "sacred", "sacrifice", "safely", "safety",
"salad", "salary", "sales", "salmon", "sample", "sanction", "sandwich",
"satellite", "satisfaction", "satisfy", "sauce", "saving", "scale", "scandal",
"scare", "scared", "scary", "scatter", "scenario", "scene", "scent",
"schedule", "scheme", "scholar", "scholarship", "school", "science",
"scientific", "scientist", "scope", "score", "scramble", "scratch", "scream",
"screen", "screening", "screw", "script", "sculpture", "search", "season",
"second", "secondary", "secret", "secretary", "section", "sector", "secular",
"secure", "security", "seemingly", "segment", "seize", "seldom", "select",
"selected", "selection", "seller", "seminar", "senate", "senator", "senior",
"sensation", "sense", "sensitive", "sensitivity", "sensor", "sentence",
"sentiment", "separate", "separation", "sequence", "series", "serious",
"seriously", "servant", "serve", "service", "serving", "session", "setting",
"settle", "settlement", "seven", "seventh", "several", "severe", "severely",
"sexual", "sexuality", "sexually", "shade", "shadow", "shake", "shall",
"shallow", "shame", "shape", "share", "shared", "shareholder", "shark",
"sharp", "sharply", "sheep", "sheer", "sheet", "shelf", "shell", "shelter",
"shift", "shine", "shirt", "shock", "shoot", "shooting", "shopping", "shore",
"short", "shortage", "shortly", "shorts", "should", "shoulder", "shout",
"shove", "shower", "shrimp", "shrink", "shrug", "shuttle", "sibling",
"sidewalk", "sight", "signal", "signature", "significance", "significant",
"significantly", "silence", "silent", "silly", "silver", "similar",
"similarity", "similarly", "simple", "simply", "simultaneously", "since",
"singer", "single", "sister", "situation", "sixth", "skill", "skilled",
"skirt", "skull", "slave", "slavery", "sleep", "sleeve", "slice", "slide",
"slight", "slightly", "slope", "slowly", "small", "smart", "smell", "smile",
"smoke", "smooth", "snake", "sneak", "soccer", "social", "socially", "society",
"sodium", "soften", "softly", "software", "solar", "soldier", "solely",
"solid", "solution", "solve", "somebody", "someday", "somehow", "someone",
"something", "sometime", "sometimes", "somewhat", "somewhere", "sophisticated",
"sorry", "sound", "source", "south", "southeast", "southern", "southwest",
"sovereignty", "soviet", "space", "spanish", "spare", "spark", "speak",
"speaker", "special", "specialist", "specialize", "specialty", "species",
"specific", "specifically", "specify", "spectacular", "spectrum", "speculate",
"speculation", "speech", "speed", "spell", "spend", "spending", "sphere",
"spill", "spine", "spirit", "spiritual", "spite", "split", "spokesman",
"sponsor", "spoon", "sport", "spouse", "spray", "spread", "spring", "sprinkle",
"squad", "square", "squeeze", "stability", "stable", "stack", "stadium",
"staff", "stage", "stair", "stake", "stance", "stand", "standard", "standing",
"stare", "start", "starter", "starting", "state", "statement", "station",
"statistical", "statistics", "statue", "status", "statute", "steadily",
"steady", "steak", "steal", "steam", "steel", "steep", "steer", "stereotype",
"stick", "stiff", "still", "stimulate", "stimulus", "stock", "stomach",
"stone", "storage", "store", "storm", "story", "stove", "straight",
"straighten", "strain", "strange", "stranger", "strategic", "strategy",
"straw", "streak", "stream", "street", "strength", "strengthen", "stress",
"stretch", "strict", "strictly", "strike", "striking", "string", "strip",
"stroke", "strong", "strongly", "structural", "structure", "struggle",
"student", "studio", "study", "stuff", "stumble", "stupid", "style", "subject",
"submit", "subsequent", "subsidy", "substance", "substantial", "substantially",
"subtle", "suburb", "suburban", "succeed", "success", "successful",
"successfully", "sudden", "suddenly", "suffer", "suffering", "sufficient",
"sugar", "suggest", "suggestion", "suicide", "suitable", "suite", "summary",
"summer", "summit", "sunlight", "sunny", "super", "superior", "supermarket",
"supervisor", "supplier", "supply", "support", "supporter", "supportive",
"suppose", "supposed", "supposedly", "supreme", "surely", "surface", "surgeon",
"surgery", "surprise", "surprised", "surprising", "surprisingly", "surround",
"surrounding", "surveillance", "survey", "survival", "survive", "survivor",
"suspect", "suspend", "suspicion", "suspicious", "sustain", "sustainable",
"swallow", "swear", "sweat", "sweater", "sweep", "sweet", "swell", "swimming",
"swing", "switch", "sword", "symbol", "symbolic", "sympathy", "symptom",
"syndrome", "system", "table", "tablespoon", "tackle", "tactic", "talent",
"talented", "target", "taste", "taxpayer", "teach", "teacher", "teaching",
"teammate", "teaspoon", "technical", "technician", "technique",
"technological", "technology", "teenage", "teenager", "telephone", "telescope",
"television", "temperature", "temple", "temporary", "tendency", "tender",
"tennis", "tension", "terms", "terrain", "terrible", "terribly", "terrific",
"territory", "terror", "terrorism", "terrorist", "testify", "testimony",
"testing", "textbook", "texture", "thank", "thanks", "thanksgiving", "theater",
"their", "theme", "themselves", "theological", "theology", "theoretical",
"theory", "therapist", "therapy", "there", "thereby", "therefore", "these",
"thick", "thigh", "thing", "think", "thinking", "third", "thirty",
"thoroughly", "those", "though", "thought", "thousand", "thread", "threat",
"threaten", "three", "threshold", "thrive", "throat", "through", "throughout",
"throw", "thumb", "ticket", "tight", "tighten", "tightly", "timber", "timing",
"tired", "tissue", "title", "tobacco", "today", "together", "toilet",
"tolerance", "tolerate", "tomato", "tomorrow", "tongue", "tonight", "tooth",
"topic", "total", "totally", "touch", "touchdown", "tough", "tourism",
"tourist", "tournament", "toward", "towards", "towel", "tower", "toxic",
"trace", "track", "trade", "trading", "tradition", "traditional",
"traditionally", "traffic", "tragedy", "tragic", "trail", "trailer", "train",
"trainer", "training", "trait", "transaction", "transfer", "transform",
"transformation", "transit", "transition", "translate", "translation",
"transmission", "transmit", "transport", "transportation", "trash", "trauma",
"travel", "traveler", "treasure", "treat", "treatment", "treaty", "tremendous",
"trend", "trial", "tribal", "tribe", "trick", "trigger", "triumph", "troop",
"tropical", "trouble", "troubled", "truck", "truly", "trunk", "trust", "truth",
"tumor", "tunnel", "turkey", "twelve", "twentieth", "twenty", "twice", "twist",
"typical", "typically", "ultimate", "ultimately", "unable", "uncertain",
"uncertainty", "uncle", "uncomfortable", "uncover", "under", "undergo",
"undergraduate", "underlying", "undermine", "understand", "understanding",
"undertake", "unemployment", "unexpected", "unfair", "unfold", "unfortunately",
"unhappy", "uniform", "union", "unique", "unite", "united", "unity",
"universal", "universe", "university", "unknown", "unless", "unlike",
"unlikely", "unprecedented", "until", "unusual", "update", "upper", "upset",
"upstairs", "urban", "useful", "usual", "usually", "utility", "utilize",
"vacation", "vaccine", "vacuum", "valid", "validity", "valley", "valuable",
"value", "vanish", "variable", "variation", "variety", "various", "vegetable",
"vehicle", "vendor", "venture", "verbal", "verdict", "version", "versus",
"vertical", "vessel", "veteran", "victim", "victory", "video", "viewer",
"village", "violate", "violation", "violence", "violent", "virtual",
"virtually", "virtue", "virus", "visible", "vision", "visit", "visitor",
"visual", "vital", "vitamin", "vocal", "voice", "volume", "voluntary",
"volunteer", "voter", "voting", "vulnerable", "wagon", "waist", "walking",
"wander", "warehouse", "warmth", "warning", "warrior", "waste", "watch",
"water", "weaken", "weakness", "wealth", "wealthy", "weapon", "weather",
"weave", "wedding", "weekend", "weekly", "weigh", "weight", "weird", "welcome",
"welfare", "western", "whale", "whatever", "wheat", "wheel", "wheelchair",
"whenever", "where", "whereas", "wherever", "whether", "which", "while",
"whisper", "white", "whoever", "whole", "whose", "widely", "widespread",
"widow", "wilderness", "wildlife", "willing", "willingness", "window",
"winner", "winter", "wisdom", "withdraw", "withdrawal", "within", "without",
"witness", "woman", "wonder", "wonderful", "wooden", "worker", "working",
"workout", "workplace", "works", "workshop", "world", "worldwide", "worried",
"worry", "worth", "would", "wound", "wrist", "write", "writer", "writing",
"written", "wrong", "yellow", "yesterday", "yield", "young", "youngster",
"yours", "yourself", "youth"
]


# initialize variables

hanged=0
saved=0
perfectly=0

do_more = 'y'
while (do_more.lower() == 'y') :
    clear_all= "\n" * 100
    word=""
    while len(word) < minsize :
        word = random.choice(WORDS)   # the word to be guessed

    WORDS=WORDS.remove(word)   # don't play this word again for this session

    so_far = "." * len(word)   # one dot for each letter in word to be guessed

    wrong = 0                  # number of wrong guesses player has made

    used = []                  # letters already guessed

    print "Welcome to Hangman. Good luck!"

    while (wrong < MAX_WRONG) and (so_far != word):
        print clear_all
        print HANGMAN[wrong]
        print "\nYou've used the following letters:\n", used
        print "\nSo far, the word is:\n", so_far

        print "\n\n"

        guess = ""
        while (
                (guess not in list(set(string.ascii_lowercase)))
            or
                (guess in used)
            ) :
            guess = raw_input("Enter your guess: ")
            guess = guess.lower()
            if (guess in used) :
                print guess , "was already guessed. ",

        used.append(guess)
        used.sort()

        if (guess in word):

           print "\nYes!", guess, "is in the word!"

           # create a new so_far to include guess
           new = ""
           for i in range(len(word)):
               if guess == word[i]:
                   new += guess
               else:
                   new += so_far[i]
           so_far = new

        else:
            print "\nSorry,", guess, "isn't in the word."
            wrong += 1

    print clear_all

    if (wrong == MAX_WRONG):
        print HANGMAN[wrong]
        print "\nYou've been hanged!"
        hanged += 1
    elif (wrong == 0):
        print PERFECT
        print "\n\n\n\n\nYou guessed it with NO MISSES!"
        saved += 1
        perfectly += 1
    else:
        print SAVEMAN
        print "\n\n\n\n\nYou guessed it!"
        saved += 1

    print "\nThe word was: ", word.upper()

    print "\nSo far, you have hanged %d and saved %d" % (hanged, saved),
    if (perfectly > 0):
        print "(%d perfectly!)" % perfectly
    else:
        print ""
        
    do_more=raw_input("\n\nAnother word? ")
    if (len(do_more) > 1):
        do_more=do_more[0]
    do_more=do_more.lower()
    


