#!/bin/ksh

BASEYR=$1

BASECAL=$(cal 2 $BASEYR)

BASECMP=$( print "$BASECAL" | sed "s/$BASEYR//")

MATCHYR=$BASEYR

while :
do
	MATCHYR=$(( $MATCHYR - 1 ))
	MATCHCAL=$(cal 2 $MATCHYR)
	MATCHCMP=$( print "$MATCHCAL" | sed "s/$MATCHYR//")
	if [ "$MATCHCMP" = "$BASECMP" ]
	then
		print "\n$MATCHCAL"
		break
	fi
done

print "\n${BASECAL}"

MATCHYR=$BASEYR

while :
do
	MATCHYR=$(( $MATCHYR + 1 ))
	MATCHCAL=$(cal 2 $MATCHYR)
	MATCHCMP=$( print "$MATCHCAL" | sed "s/$MATCHYR//")
	if [ "$MATCHCMP" = "$BASECMP" ]
	then
		print "\n$MATCHCAL"
		break
	fi
done
