#!/usr/bin/python2
# Hangman Game
#
# The classic game of Hangman. The computer picks a random word
# and the player tries to guess it, one letter at a time. If the player
# can't guess the word in time, the little stick figure gets hanged.
#
# Michael Dawson

# imports
import random
import string
from sys import argv

cmdargs = ( argv )
if len(argv) > 1 :
    minsize = int(cmdargs[1])
else :
    minsize = 1

#constants
PERFECT = r"""
 _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_
  //\    //\    //\    //\    //\    //\    //\    //\    //\


    //   ) )                  //  ) )                        //
   //___/ /  ___      __   __//__  ___      ___    __  ___  //
  / ____ / //___) ) //  ) ) //   //___) ) //   ) )  / /    //
 //       //       //      //   //       //        / /
//       ((____   //      //   ((____   ((____    / /    //



 _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_  _\\/_
  //\    //\    //\    //\    //\    //\    //\    //\    //\
"""

HANGMAN = (
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /       //\\ 
| |/       //  \\ 
| |       //    \\ 
| |       \\ __ // 
| |        ` -- ' 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |           `-' 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |         \ . . / 
| |          |   | 
| |          | . | 
| |          |   | 
| |           \_/ 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . / 
| |       // |   | 
| |      //  | . | 
| |     ')   |   | 
| |           \_/ 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        /  _  \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . Y\ 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |           \_/ 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        .'''. 
| |/        / / \ \ 
| |         | `\' | 
| |          \ - / 
| |         .-`--'. 
| |        /Y . . Y\ 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |          ||^-  
| |          || 
| |          || 
| |          || 
| |         / | 
^^^^^^^^^^|^^^^^^^^^|^^^| 
|^|^^^^^^^`^^^^^^^^^'^|^| 
| |                   | | 
: :                   : : 
. .                   . . 
""",
r"""
 ___________.._______ 
| .__________))______| 
| | / /      || 
| |/ /       || 
| | /        ||.-''. 
| |/         |/  _  \        ____    ___   ____ 
| |          ||  `/,|       |  _ \  |_ _| |  _ \ 
| |          (\\`_.'        | |_) |  | |  | |_) | 
| |         .-`--'.         |  _ < _ | | _|  __/ 
| |        /Y . . Y\        |_| \_(_)___(_)_| (_) 
| |       // |   | \\ 
| |      //  | . |  \\ 
| |     ')   |   |   (` 
| |          ||^|| 
| |          || || 
| |          || || 
| |          || || 
| |         / | | \ 
^^^^^^^^^^|_`-' `-' |^^^| 
|^|^^^^^^^\ \       '^|^| 
| |        \ \        | | 
: :         \ \       : : 
. .          `'       . .
""") 


SAVEMAN = r"""
             .'''.         __        ___                   _  
            /  _  \        \ \      / / |__   _____      _| |
            | `\' |         \ \ /\ / /| '_ \ / _ \ \ /\ / / |
             \`-'/           \ V  V / | | | |  __/\ V  V /|_|
            .-`--'.           \_/\_/  |_| |_|\___| \_/\_/ (_)
           /Y . . Y\        _____ _                 _
          // |   | \\      |_   _| |__   __ _ _ __ | | _____
         //  | . |  \\       | | | '_ \ / _` | '_ \| |/ / __|
        ')   |   |   (`      | | | | | | (_| | | | |   <\__ \_
             ||^||           |_| |_| |_|\__,_|_| |_|_|\_\___( )
             || ||                                          |/
             || ||          ____       _ _
             || ||         |  _ \ __ _| | |
            / | | \        | |_) / _` | | |
^^^^^^^^^^^^^^^^^^^^^^^^|  |  __/ (_| | |_|
|^|^^^^^^^^^^^^^^^^^^^|^|  |_|   \__,_|_(_)
| |                   | | 
: :                   : : 
. .                   . . 
"""


MAX_WRONG = len(HANGMAN) - 1

WORDS= []
ALLWORDS = [ "a", "abandon", "ability", "able", "abortion", "about", "above",
"abroad", "absence", "absolute", "absolutely", "absorb", "abstract",
"abuse", "academic", "accelerate", "accent", "accept", "acceptable",
"acceptance", "access", "accessible", "accident", "accommodate",
"accompany", "accomplish", "accomplishment", "according", "account",
"accountability", "accounting", "accuracy", "accurate", "accurately",
"accusation", "accuse", "achieve", "achievement", "acid", "acknowledge",
"acquire", "acquisition", "across", "act", "action", "active", "actively",
"activist", "activity", "actor", "actress", "actual", "actually", "ad",
"adapt", "add", "added", "addition", "additional", "address", "adequate",
"adjust", "adjustment", "administer", "administration", "administrative",
"administrator", "admire", "admission", "admit", "adolescent", "adopt",
"adoption", "adult", "advance", "advanced", "advantage", "adventure",
"advertising", "advice", "advise", "adviser", "advocate", "aesthetic",
"affair", "affect", "afford", "afraid", "african", "after", "afternoon",
"afterward", "again", "against", "age", "agency", "agenda", "agent",
"aggression", "aggressive", "ago", "agree", "agreement", "agricultural",
"agriculture", "ah", "ahead", "aid", "aide", "aim", "air", "aircraft",
"airline", "airplane", "airport", "aisle", "alarm", "album", "alcohol",
"alien", "alike", "alive", "all", "allegation", "alleged", "allegedly",
"alley", "alliance", "allow", "ally", "almost", "alone", "along",
"alongside", "already", "also", "alter", "alternative", "although",
"altogether", "aluminum", "always", "amazing", "ambassador", "ambition",
"ambitious", "amendment", "american", "among", "amount", "analysis",
"analyst", "analyze", "ancestor", "ancient", "and", "angel", "anger",
"angle", "angry", "animal", "ankle", "anniversary", "announce",
"announcement", "annual", "annually", "anonymous", "another", "answer",
"anticipate", "anxiety", "anxious", "any", "anybody", "anymore", "anyone",
"anything", "anyway", "anywhere", "apart", "apartment", "apologize",
"apology", "apparent", "apparently", "appeal", "appear", "appearance",
"apple", "application", "apply", "appoint", "appointment", "appreciate",
"appreciation", "approach", "appropriate", "approval", "approve",
"approximately", "arab", "architect", "architecture", "area", "arena",
"argue", "argument", "arise", "arm", "armed", "army", "around", "arrange",
"arrangement", "array", "arrest", "arrival", "arrive", "arrow", "art",
"article", "articulate", "artifact", "artificial", "artist", "artistic",
"as", "asian", "aside", "ask", "asleep", "aspect", "assault", "assemble",
"assembly", "assert", "assess", "assessment", "asset", "assign",
"assignment", "assist", "assistance", "assistant", "associate",
"associated", "association", "assume", "assumption", "assure",
"astronomer", "at", "athlete", "athletic", "atmosphere", "attach",
"attack", "attempt", "attend", "attendance", "attention", "attitude",
"attorney", "attract", "attraction", "attractive", "attribute",
"auction", "audience", "author", "authority", "authorize", "auto",
"automatic", "automatically", "automobile", "autonomy", "availability",
"available", "average", "avoid", "await", "awake", "award", "aware",
"awareness", "away", "awful", "baby", "back", "background", "backyard",
"bacteria", "bad", "badly", "bag", "bake", "balance", "balanced",
"ball", "balloon", "ballot", "ban", "banana", "band", "bank", "banker",
"banking", "bar", "barely", "barrel", "barrier", "base", "baseball",
"basement", "basic", "basically", "basis", "basket", "basketball",
"bathroom", "battery", "battle", "be", "beach", "bean", "bear", "beard",
"beast", "beat", "beautiful", "beauty", "because", "become", "bed",
"bedroom", "beer", "before", "begin", "beginning", "behalf", "behave",
"behavior", "behavioral", "behind", "being", "belief", "believe",
"bell", "belly", "belong", "below", "belt", "bench", "bend", "beneath",
"benefit", "beside", "besides", "best", "bet", "better", "between",
"beyond", "bible", "bicycle", "big", "bike", "bill", "billion", "bind",
"biography", "biological", "biology", "bird", "birth", "birthday",
"bishop", "bit", "bite", "bitter", "black", "blade", "blame", "blank",
"blanket", "blast", "blend", "bless", "blessing", "blind", "blink",
"block", "blond", "blood", "bloody", "blow", "blue", "board", "boast",
"boat", "body", "bomb", "bombing", "bond", "bone", "bonus", "book",
"boom", "boost", "boot", "booth", "border", "boring", "born", "borrow",
"boss", "both", "bother", "bottle", "bottom", "bounce", "boundary",
"bowl", "box", "boy", "boyfriend", "brain", "brake", "branch", "brand",
"brave", "bread", "break", "breakfast", "breast", "breath", "breathe",
"breathing", "breeze", "brick", "bride", "bridge", "brief", "briefly",
"bright", "brilliant", "bring", "british", "broad", "broadcast", "broken",
"broker", "bronze", "brother", "brown", "brush", "brutal", "bubble",
"buck", "bucket", "buddy", "budget", "build", "builder", "building",
"bullet", "bunch", "burden", "bureau", "burn", "burning", "burst",
"bury", "bus", "business", "businessman", "busy", "but", "butter",
"butterfly", "button", "buy", "buyer", "by", "cabin", "cabinet", "cable",
"cake", "calculate", "calculation", "calendar", "call", "camera", "camp",
"campaign", "campus", "can", "canadian", "cancel", "cancer", "candidate",
"candle", "candy", "canvas", "cap", "capability", "capable", "capacity",
"capital", "captain", "capture", "car", "carbohydrate", "carbon", "card",
"care", "career", "careful", "carefully", "cargo", "carpet", "carrier",
"carrot", "carry", "cartoon", "carve", "case", "cash", "casino", "cast",
"casual", "casualty", "cat", "catalog", "catch", "category", "catholic",
"cattle", "cause", "cease", "ceiling", "celebrate", "celebration",
"celebrity", "cell", "cemetery", "center", "central", "century", "ceo",
"ceremony", "certain", "certainly", "chain", "chair", "chairman",
"challenge", "chamber", "champion", "championship", "chance", "change",
"changing", "channel", "chaos", "chapter", "character", "characteristic",
"characterize", "charge", "charity", "charm", "chart", "charter", "chase",
"cheap", "cheat", "check", "cheek", "cheer", "cheese", "chef", "chemical",
"chemistry", "chest", "chicken", "chief", "child", "childhood", "chill",
"chinese", "chip", "chocolate", "choice", "cholesterol", "choose",
"christian", "christianity", "christmas", "chronic", "chunk", "church",
"cigarette", "circle", "circuit", "circumstance", "cite", "citizen",
"citizenship", "city", "civic", "civil", "civilian", "civilization",
"claim", "class", "classic", "classical", "classify", "classroom",
"clean", "clear", "clearly", "clerk", "click", "client", "cliff",
"climate", "climb", "cling", "clinic", "clinical", "clock", "close",
"closed", "closely", "closer", "closest", "closet", "cloth", "clothes",
"clothing", "cloud", "club", "clue", "cluster", "coach", "coal",
"coalition", "coast", "coastal", "coat", "cocaine", "code", "coffee",
"cognitive", "cold", "collaboration", "collapse", "collar", "colleague",
"collect", "collection", "collective", "collector", "college",
"colonial", "colony", "color", "colorful", "column", "columnist",
"combat", "combination", "combine", "combined", "come", "comedy",
"comfort", "comfortable", "coming", "command", "commander", "comment",
"commercial", "commission", "commissioner", "commit", "commitment",
"committee", "commodity", "common", "commonly", "communicate",
"communication", "community", "companion", "company", "comparable",
"compare", "comparison", "compel", "compelling", "compensation",
"compete", "competition", "competitive", "competitor", "complain",
"complaint", "complete", "completely", "complex", "complexity",
"compliance", "complicated", "comply", "component", "compose",
"composition", "compound", "comprehensive", "comprise", "compromise",
"computer", "concede", "conceive", "concentrate", "concentration",
"concept", "conception", "concern", "concerned", "concerning", "concert",
"conclude", "conclusion", "concrete", "condemn", "condition", "conduct",
"conference", "confess", "confession", "confidence", "confident",
"confirm", "conflict", "confront", "confrontation", "confuse",
"confusion", "congress", "congressional", "connect", "connection",
"conscience", "conscious", "consciousness", "consecutive", "consensus",
"consent", "consequence", "consequently", "conservation", "conservative",
"consider", "considerable", "considerably", "consideration", "consist",
"consistent", "consistently", "conspiracy", "constant", "constantly",
"constitute", "constitution", "constitutional", "constraint",
"construct", "construction", "consult", "consultant", "consume",
"consumer", "consumption", "contact", "contain", "container",
"contemplate", "contemporary", "contend", "content", "contest",
"context", "continent", "continue", "continued", "continuing",
"continuous", "contract", "contractor", "contrast", "contribute",
"contribution", "contributor", "control", "controversial", "controversy",
"convenience", "convention", "conventional", "conversation", "conversion",
"convert", "convey", "convict", "conviction", "convince", "convinced",
"cook", "cookie", "cooking", "cool", "cooperate", "cooperation",
"cooperative", "coordinate", "coordinator", "cop", "cope", "copy",
"core", "corn", "corner", "corporate", "corporation", "correct",
"correctly", "correlation", "correspondent", "corridor", "corruption",
"cost", "costly", "costume", "cottage", "cotton", "couch", "could",
"council", "counsel", "counseling", "counselor", "count", "counter",
"counterpart", "country", "county", "couple", "courage", "course",
"court", "courtroom", "cousin", "cover", "coverage", "cow", "crack",
"craft", "crash", "crawl", "crazy", "cream", "create", "creation",
"creative", "creativity", "creature", "credibility", "credit", "crew",
"crime", "criminal", "crisis", "criteria", "critic", "critical",
"criticism", "criticize", "crop", "cross", "crowd", "crowded", "crucial",
"cruel", "cruise", "crush", "cry", "crystal", "cuban", "cultural",
"culture", "cup", "curiosity", "curious", "currency", "current",
"currently", "curriculum", "curtain", "curve", "custody", "custom",
"customer", "cut", "cycle", "dad", "daily", "damage", "dance", "dancer",
"dancing", "danger", "dangerous", "dare", "dark", "darkness", "data",
"database", "date", "daughter", "day", "dead", "deadline", "deadly",
"deal", "dealer", "dear", "death", "debate", "debris", "debt", "debut",
"decade", "decent", "decide", "decision", "deck", "declare", "decline",
"decorate", "decrease", "dedicate", "deep", "deeply", "deer", "defeat",
"defend", "defendant", "defender", "defense", "defensive", "deficit",
"define", "definitely", "definition", "degree", "delay", "deliberately",
"delicate", "delight", "deliver", "delivery", "demand", "democracy",
"democrat", "democratic", "demographic", "demonstrate", "demonstration",
"denial", "dense", "density", "deny", "depart", "department", "departure",
"depend", "dependent", "depending", "depict", "deploy", "deposit",
"depressed", "depression", "depth", "deputy", "derive", "descend",
"describe", "description", "desert", "deserve", "design", "designer",
"desire", "desk", "desperate", "desperately", "despite", "dessert",
"destination", "destroy", "destruction", "detail", "detailed", "detect",
"detective", "determination", "determine", "devastating", "develop",
"developer", "developing", "development", "developmental", "device",
"devil", "devote", "diabetes", "diagnose", "diagnosis", "dialogue",
"diamond", "diary", "dictate", "die", "diet", "differ", "difference",
"different", "differently", "difficult", "difficulty", "dig", "digital",
"dignity", "dilemma", "dimension", "diminish", "dining", "dinner",
"diplomat", "diplomatic", "direct", "direction", "directly", "director",
"dirt", "dirty", "disability", "disabled", "disagree", "disappear",
"disappointed", "disappointment", "disaster", "discipline", "disclose",
"discount", "discourage", "discourse", "discover", "discovery",
"discrimination", "discuss", "discussion", "disease", "dish", "dismiss",
"disorder", "display", "dispute", "dissolve", "distance", "distant",
"distinct", "distinction", "distinctive", "distinguish", "distract",
"distribute", "distribution", "district", "disturb", "disturbing",
"diverse", "diversity", "divide", "divine", "division", "divorce", "dna",
"do", "doctor", "doctrine", "document", "documentary", "dog", "domain",
"domestic", "dominant", "dominate", "donate", "donation", "donor",
"door", "doorway", "double", "doubt", "dough", "down", "downtown",
"dozen", "draft", "drag", "drain", "drama", "dramatic", "dramatically",
"draw", "drawer", "drawing", "dream", "dress", "dried", "drift", "drill",
"drink", "drinking", "drive", "driver", "driveway", "driving", "drop",
"drown", "drug", "drunk", "dry", "due", "during", "dust", "dutch", "duty",
"dying", "dynamic", "dynamics", "each", "eager", "ear", "early", "earn",
"earnings", "earth", "earthquake", "ease", "easily", "east", "eastern",
"easy", "eat", "eating", "ecological", "economic", "economically",
"economics", "economist", "economy", "ecosystem", "edge", "edition",
"editor", "educate", "education", "educational", "educator", "effect",
"effective", "effectively", "effectiveness", "efficiency", "efficient",
"effort", "egg", "eight", "eighth", "either", "elaborate", "elbow",
"elder", "elderly", "elect", "election", "electric", "electrical",
"electricity", "electronic", "electronics", "elegant", "element",
"elementary", "elephant", "elevator", "eleven", "eligible", "eliminate",
"elite", "else", "elsewhere", "email", "embarrassed", "embrace",
"emerge", "emergency", "emerging", "emission", "emotion", "emotional",
"emotionally", "emphasis", "emphasize", "empire", "employ", "employee",
"employer", "employment", "empty", "enable", "enact", "encounter",
"encourage", "encouraging", "end", "endless", "endorse", "endure",
"enemy", "energy", "enforce", "enforcement", "engage", "engagement",
"engine", "engineer", "engineering", "english", "enhance", "enjoy",
"enormous", "enough", "enroll", "ensure", "enter", "enterprise",
"entertainment", "enthusiasm", "entire", "entirely", "entitle",
"entity", "entrance", "entrepreneur", "entry", "envelope", "environment",
"environmental", "envision", "epidemic", "episode", "equal", "equality",
"equally", "equation", "equip", "equipment", "equity", "equivalent",
"era", "error", "escape", "especially", "essay", "essence", "essential",
"essentially", "establish", "establishment", "estate", "estimate",
"estimated", "etc", "ethical", "ethics", "ethnic", "european", "evaluate",
"evaluation", "even", "evening", "event", "eventually", "ever", "every",
"everybody", "everyday", "everyone", "everything", "everywhere",
"evidence", "evident", "evolution", "evolve", "exact", "exactly",
"examination", "examine", "example", "exceed", "excellent", "except",
"exception", "excessive", "exchange", "excited", "excitement", "exciting",
"exclude", "exclusive", "exclusively", "excuse", "execute", "execution",
"executive", "exercise", "exhaust", "exhibit", "exhibition", "exist",
"existence", "existing", "exotic", "expand", "expansion", "expect",
"expectation", "expected", "expedition", "expense", "expensive",
"experience", "experienced", "experiment", "experimental", "expert",
"expertise", "explain", "explanation", "explicit", "explode", "exploit",
"exploration", "explore", "explosion", "export", "expose", "exposure",
"express", "expression", "extend", "extended", "extension", "extensive",
"extent", "external", "extra", "extraordinary", "extreme", "extremely",
"eye", "eyebrow", "fabric", "face", "facilitate", "facility", "fact",
"factor", "factory", "faculty", "fade", "fail", "failure", "faint",
"fair", "fairly", "faith", "fall", "false", "familiar", "family",
"famous", "fan", "fantastic", "fantasy", "far", "farm", "farmer",
"fascinating", "fashion", "fast", "faster", "fat", "fatal", "fate",
"father", "fatigue", "fault", "favor", "favorable", "favorite", "fear",
"feather", "feature", "federal", "fee", "feed", "feedback", "feel",
"feeling", "fellow", "female", "feminist", "fence", "festival", "fever",
"few", "fewer", "fiber", "fiction", "field", "fierce", "fifteen", "fifth",
"fifty", "fight", "fighter", "fighting", "figure", "file", "fill", "film",
"filter", "final", "finally", "finance", "financial", "find", "finding",
"fine", "finger", "finish", "fire", "firm", "firmly", "first", "fiscal",
"fish", "fisherman", "fishing", "fit", "fitness", "five", "fix", "fixed",
"flag", "flame", "flash", "flat", "flavor", "flee", "fleet", "flesh",
"flexibility", "flexible", "flight", "float", "flood", "floor", "flour",
"flow", "flower", "fluid", "fly", "flying", "focus", "folk", "follow",
"following", "food", "foot", "football", "for", "forbid", "force",
"forehead", "foreign", "foreigner", "forest", "forever", "forget",
"forgive", "form", "formal", "format", "formation", "former", "formerly",
"formula", "forth", "fortunately", "fortune", "forty", "forum", "forward",
"foster", "found", "foundation", "founder", "four", "fourth", "fraction",
"fragile", "fragment", "frame", "framework", "franchise", "frankly",
"fraud", "free", "freedom", "freely", "freeze", "french", "frequency",
"frequent", "frequently", "fresh", "freshman", "friend", "friendly",
"friendship", "from", "front", "frontier", "frown", "frozen", "fruit",
"frustrate", "frustration", "fuel", "full", "fulltime", "fully",
"fun", "function", "functional", "fund", "fundamental", "funding",
"funeral", "funny", "furniture", "furthermore", "future", "gain",
"galaxy", "gallery", "game", "gang", "gap", "garage", "garbage",
"garden", "garlic", "gas", "gasoline", "gate", "gather", "gathering",
"gay", "gaze", "gear", "gender", "gene", "general", "generally",
"generate", "generation", "generous", "genetic", "genius", "genre",
"gentle", "gentleman", "gently", "genuine", "german", "gesture", "get",
"ghost", "giant", "gift", "gifted", "girl", "girlfriend", "give",
"given", "glad", "glance", "glass", "glimpse", "global", "globe",
"glory", "glove", "go", "goal", "god", "gold", "golden", "golf",
"good", "govern", "government", "governor", "grab", "grace", "grade",
"gradually", "graduate", "graduation", "grain", "grand", "grandchild",
"grandfather", "grandmother", "grandparent", "grant", "grape", "grasp",
"grass", "grateful", "grave", "gravity", "gray", "great", "greatest",
"greatly", "greek", "green", "greet", "grief", "grocery", "gross",
"ground", "group", "grow", "growing", "growth", "guarantee", "guard",
"guess", "guest", "guidance", "guide", "guideline", "guilt", "guilty",
"guitar", "gun", "guy", "habit", "habitat", "hair", "half", "halfway",
"hall", "hallway", "hand", "handful", "handle", "handsome", "hang",
"happen", "happily", "happiness", "happy", "harassment", "hard",
"hardly", "hardware", "harmony", "harsh", "harvest", "hat", "hate",
"have", "hazard", "he", "head", "headache", "headline", "headquarters",
"health", "healthcare", "healthy", "hear", "hearing", "heart",
"heat", "heaven", "heavily", "heavy", "heel", "height", "helicopter",
"hell", "hello", "helmet", "help", "helpful", "hence", "her", "here",
"heritage", "hero", "herself", "hesitate", "hey", "hi", "hidden",
"hide", "high", "highlight", "highly", "highway", "hill", "him",
"himself", "hip", "hire", "his", "hispanic", "historian", "historic",
"historical", "historically", "history", "hit", "hockey", "hold",
"hole", "holiday", "holy", "home", "homeland", "homeless", "homework",
"honest", "honestly", "honey", "honor", "hope", "hopefully", "horizon",
"hormone", "horrible", "horror", "horse", "hospital", "host", "hostage",
"hostile", "hot", "hotel", "hour", "house", "household", "housing", "how",
"however", "huge", "human", "humanity", "humor", "hundred", "hunger",
"hungry", "hunter", "hunting", "hurricane", "hurry", "hurt", "husband",
"hypothesis", "i", "ice", "idea", "ideal", "identical", "identification",
"identify", "identity", "ideological", "ideology", "ie", "if", "ignore",
"ill", "illegal", "illness", "illusion", "illustrate", "image",
"imagination", "imagine", "immediate", "immediately", "immigrant",
"immigration", "immune", "impact", "implement", "implementation",
"implication", "imply", "import", "importance", "important",
"importantly", "impose", "impossible", "impress", "impression",
"impressive", "improve", "improved", "improvement", "impulse",
"in", "incentive", "incident", "include", "including", "income",
"incorporate", "increase", "increased", "increasing", "increasingly",
"incredible", "incredibly", "indeed", "independence", "independent",
"index", "indian", "indicate", "indication", "indicator", "indigenous",
"individual", "industrial", "industry", "inevitable", "inevitably",
"infant", "infection", "inflation", "influence", "influential", "inform",
"informal", "information", "infrastructure", "ingredient", "inherent",
"inherit", "initial", "initially", "initiate", "initiative", "injure",
"injury", "inmate", "inner", "innocent", "innovation", "innovative",
"input", "inquiry", "insect", "insert", "inside", "insight", "insist",
"inspection", "inspector", "inspiration", "inspire", "install",
"installation", "instance", "instant", "instantly", "instead",
"instinct", "institution", "institutional", "instruct", "instruction",
"instructional", "instructor", "instrument", "insurance", "intact",
"integrate", "integrated", "integration", "integrity", "intellectual",
"intelligence", "intelligent", "intend", "intense", "intensity",
"intent", "intention", "interact", "interaction", "interest",
"interested", "interesting", "interfere", "interior", "internal",
"international", "internet", "interpret", "interpretation", "interrupt",
"interval", "intervention", "interview", "intimate", "into", "introduce",
"introduction", "invade", "invasion", "invent", "invention", "inventory",
"invest", "investigate", "investigation", "investigator", "investment",
"investor", "invisible", "invitation", "invite", "involve", "involved",
"involvement", "iraqi", "irish", "iron", "ironically", "irony", "islam",
"islamic", "island", "isolate", "isolated", "isolation", "israeli",
"issue", "it", "italian", "item", "its", "itself", "jacket", "jail",
"japanese", "jeans", "jet", "jew", "jewelry", "jewish", "job", "join",
"joint", "joke", "journal", "journalism", "journalist", "journey", "joy",
"judge", "judgment", "judicial", "juice", "jump", "jungle", "junior",
"jurisdiction", "juror", "jury", "just", "justice", "justify", "keep",
"key", "kick", "kid", "kill", "killer", "killing", "kind", "king",
"kingdom", "kiss", "kitchen", "knee", "kneel", "knife", "knock",
"know", "knowledge", "known", "korean", "lab", "label", "labor",
"laboratory", "lack", "ladder", "lady", "lake", "land", "landing",
"landmark", "landscape", "language", "lap", "large", "largely",
"laser", "last", "late", "lately", "later", "latin", "latter", "laugh",
"laughter", "launch", "laundry", "law", "lawmaker", "lawn", "lawsuit",
"lawyer", "lay", "layer", "lead", "leader", "leadership", "leading",
"leaf", "league", "lean", "learn", "learning", "least", "leather",
"leave", "lecture", "left", "leg", "legacy", "legal", "legally",
"legend", "legislation", "legislative", "legislator", "legislature",
"legitimate", "lemon", "length", "less", "lesson", "let", "letter",
"level", "liability", "liberal", "liberty", "library", "license",
"lie", "life", "lifestyle", "lifetime", "lift", "light", "lighting",
"lightly", "lightning", "like", "likelihood", "likely", "likewise",
"limit", "limitation", "limited", "line", "link", "lip", "liquid", "list",
"listen", "listener", "literally", "literary", "literature", "little",
"live", "liver", "living", "load", "loan", "lobby", "local", "locate",
"location", "lock", "logic", "logical", "lonely", "long", "longtime",
"look", "loose", "lose", "loss", "lost", "lot", "lots", "loud", "love",
"lovely", "lover", "low", "lower", "loyal", "loyalty", "luck", "lucky",
"lunch", "lung", "machine", "mad", "magazine", "magic", "magnetic",
"magnitude", "mail", "main", "mainly", "mainstream", "maintain",
"maintenance", "major", "majority", "make", "maker", "makeup",
"male", "mall", "man", "manage", "management", "manager", "managing",
"mandate", "manipulate", "manner", "mansion", "manual", "manufacturer",
"manufacturing", "many", "map", "marble", "march", "margin", "marine",
"mark", "marker", "market", "marketing", "marketplace", "marriage",
"married", "marry", "mask", "mass", "massive", "master", "match",
"material", "math", "mathematics", "matter", "maximum", "may", "maybe",
"mayor", "me", "meal", "mean", "meaning", "meaningful", "meantime",
"meanwhile", "measure", "measurement", "meat", "mechanic", "mechanical",
"mechanism", "medal", "media", "medical", "medication", "medicine",
"medium", "meet", "meeting", "member", "membership", "memory", "mental",
"mentally", "mention", "mentor", "menu", "merchant", "mere", "merely",
"merit", "mess", "message", "metal", "metaphor", "meter", "method",
"metropolitan", "mexican", "middle", "midnight", "midst", "might",
"migration", "military", "milk", "million", "mind", "mine", "mineral",
"minimal", "minimize", "minimum", "minister", "ministry", "minor",
"minority", "minute", "miracle", "mirror", "miss", "missile", "missing",
"mission", "missionary", "mistake", "mix", "mixed", "mixture", "mobile",
"mode", "model", "moderate", "modern", "modest", "modify", "molecule",
"mom", "moment", "momentum", "money", "monitor", "monkey", "monster",
"month", "monthly", "monument", "mood", "moon", "moral", "more",
"moreover", "morning", "mortality", "mortgage", "most", "mostly",
"mother", "motion", "motivate", "motivation", "motive", "motor",
"mount", "mountain", "mouse", "mouth", "move", "movement", "movie",
"mr", "mrs", "ms", "much", "multiple", "municipal", "murder", "muscle",
"museum", "mushroom", "music", "musical", "musician", "muslim", "must",
"mutter", "mutual", "my", "myself", "mysterious", "mystery", "myth",
"naked", "name", "narrative", "narrow", "nasty", "nation", "national",
"nationwide", "native", "natural", "naturally", "nature", "naval",
"near", "nearby", "nearly", "necessarily", "necessary", "necessity",
"neck", "need", "needle", "negative", "negotiate", "negotiation",
"neighbor", "neighborhood", "neighboring", "neither", "nerve",
"nervous", "net", "network", "neutral", "never", "nevertheless", "new",
"newly", "news", "newspaper", "next", "nice", "night", "nightmare",
"nine", "no", "nobody", "nod", "noise", "nomination", "nominee",
"none", "nonetheless", "nonprofit", "nor", "normal", "normally",
"north", "northeast", "northern", "northwest", "nose", "not", "note",
"notebook", "nothing", "notice", "notion", "novel", "now", "nowhere",
"nuclear", "number", "numerous", "nurse", "nut", "nutrient", "object",
"objection", "objective", "obligation", "observation", "observe",
"observer", "obstacle", "obtain", "obvious", "obviously", "occasion",
"occasional", "occasionally", "occupation", "occupy", "occur", "ocean",
"odd", "odds", "of", "off", "offender", "offense", "offensive", "offer",
"offering", "office", "officer", "official", "officially", "often",
"oh", "oil", "ok", "okay", "old", "olympic", "olympics", "on", "once",
"one", "ongoing", "onion", "online", "only", "onto", "open", "opening",
"openly", "opera", "operate", "operating", "operation", "operator",
"opinion", "opponent", "opportunity", "oppose", "opposed", "opposite",
"opposition", "optimistic", "option", "or", "orange", "orbit",
"order", "ordinary", "organ", "organic", "organism", "organization",
"organizational", "organize", "organized", "orientation", "origin",
"original", "originally", "other", "others", "otherwise", "ought", "our",
"ourselves", "out", "outcome", "outdoor", "outer", "outfit", "outlet",
"outline", "output", "outside", "outsider", "outstanding", "oven",
"over", "overall", "overcome", "overlook", "overnight", "oversee",
"overwhelm", "overwhelming", "owe", "own", "owner", "ownership",
"oxygen", "pace", "pack", "package", "page", "pain", "painful",
"paint", "painter", "painting", "pair", "palace", "pale", "palestinian",
"palm", "pan", "panel", "panic", "pant", "paper", "parade", "parent",
"parental", "parish", "park", "parking", "part", "partial", "partially",
"participant", "participate", "participation", "particle", "particular",
"particularly", "partly", "partner", "partnership", "party", "pass",
"passage", "passenger", "passing", "passion", "past", "pasta", "pastor",
"patch", "patent", "path", "patience", "patient", "patrol", "patron",
"pattern", "pause", "pay", "payment", "pc", "peace", "peaceful",
"peak", "peanut", "peasant", "peer", "penalty", "pencil", "pension",
"people", "pepper", "per", "perceive", "perceived", "percentage",
"perception", "perfect", "perfectly", "perform", "performance",
"performer", "perhaps", "period", "permanent", "permission", "permit",
"persian", "persist", "person", "personal", "personality", "personally",
"personnel", "perspective", "persuade", "pet", "phase", "phenomenon",
"philosophical", "philosophy", "phone", "photo", "photograph",
"photographer", "photography", "phrase", "physical", "physically",
"physician", "physics", "piano", "pick", "pickup", "picture", "pie",
"piece", "pile", "pillow", "pilot", "pine", "pink", "pioneer", "pipe",
"pistol", "pitch", "pitcher", "pizza", "place", "placement", "plain",
"plaintiff", "plan", "plane", "planet", "planner", "planning", "plant",
"plastic", "plate", "platform", "play", "player", "playoff", "plead",
"pleasant", "please", "pleased", "pleasure", "plenty", "plot", "plunge",
"plus", "pocket", "poem", "poet", "poetry", "point", "pole", "police",
"policeman", "policy", "political", "politically", "politician",
"politics", "poll", "pollution", "pool", "poor", "pop", "popular",
"popularity", "population", "porch", "port", "portfolio", "portion",
"portrait", "portray", "pose", "position", "positive", "possess",
"possession", "possibility", "possible", "possibly", "post", "poster",
"pot", "potato", "potential", "potentially", "pound", "pour", "poverty",
"powder", "power", "powerful", "practical", "practically", "practice",
"practitioner", "praise", "pray", "prayer", "preach", "precious",
"precise", "precisely", "predator", "predict", "prediction", "prefer",
"preference", "pregnancy", "pregnant", "preliminary", "premise",
"premium", "preparation", "prepare", "prescription", "presence",
"present", "presentation", "preserve", "presidency", "president",
"presidential", "press", "pressure", "presumably", "pretend", "pretty",
"prevail", "prevent", "prevention", "previous", "previously",
"price", "pride", "priest", "primarily", "primary", "prime",
"principal", "principle", "print", "prior", "priority", "prison",
"prisoner", "privacy", "private", "privately", "privilege", "prize",
"probably", "problem", "procedure", "proceed", "process", "processing",
"processor", "proclaim", "produce", "producer", "product", "production",
"productive", "productivity", "profession", "professional", "professor",
"profile", "profit", "profound", "program", "programming", "progress",
"progressive", "prohibit", "project", "projection", "prominent",
"promise", "promising", "promote", "promotion", "prompt", "proof",
"proper", "properly", "property", "proportion", "proposal", "propose",
"proposed", "prosecution", "prosecutor", "prospect", "protect",
"protection", "protective", "protein", "protest", "protocol", "proud",
"prove", "provide", "provided", "provider", "province", "provision",
"provoke", "psychological", "psychologist", "psychology", "public",
"publication", "publicity", "publicly", "publish", "publisher", "pull",
"pulse", "punch", "punish", "punishment", "purchase", "pure", "purple",
"purpose", "purse", "pursue", "pursuit", "push", "put", "puzzle",
"qualify", "quality", "quantity", "quarter", "quarterback", "queen",
"quest", "question", "questionnaire", "quick", "quickly", "quiet",
"quietly", "quit", "quite", "quote", "rabbit", "race", "racial", "racism",
"radar", "radiation", "radical", "radio", "rail", "railroad", "rain",
"raise", "rally", "ranch", "random", "range", "rank", "rapid", "rapidly",
"rare", "rarely", "rate", "rather", "rating", "ratio", "rational", "raw",
"reach", "react", "reaction", "read", "reader", "readily", "reading",
"ready", "real", "realistic", "reality", "realize", "really", "realm",
"reason", "reasonable", "rebel", "rebuild", "recall", "receive",
"receiver", "recent", "recently", "reception", "recession", "recipe",
"recipient", "recognition", "recognize", "recommend", "recommendation",
"record", "recording", "recover", "recovery", "recruit", "red", "reduce",
"reduction", "refer", "reference", "reflect", "reflection", "reform",
"refrigerator", "refuge", "refugee", "refuse", "regain", "regard",
"regarding", "regardless", "regime", "region", "regional", "register",
"regret", "regular", "regularly", "regulate", "regulation", "regulator",
"regulatory", "rehabilitation", "reinforce", "reject", "relate",
"related", "relation", "relationship", "relative", "relatively", "relax",
"release", "relevant", "reliability", "reliable", "relief", "relieve",
"religion", "religious", "reluctant", "rely", "remain", "remaining",
"remark", "remarkable", "remember", "remind", "reminder", "remote",
"removal", "remove", "render", "rental", "repair", "repeat", "repeatedly",
"replace", "replacement", "reply", "report", "reportedly", "reporter",
"reporting", "represent", "representation", "representative",
"republic", "republican", "reputation", "request", "require",
"required", "requirement", "rescue", "research", "researcher",
"resemble", "reservation", "reserve", "residence", "resident",
"residential", "resign", "resist", "resistance", "resolution",
"resolve", "resort", "resource", "respect", "respectively", "respond",
"respondent", "response", "responsibility", "responsible", "rest",
"restaurant", "restore", "restrict", "restriction", "result", "resume",
"retail", "retailer", "retain", "retire", "retired", "retirement",
"retreat", "return", "reveal", "revelation", "revenue", "reverse",
"review", "revolution", "revolutionary", "reward", "rhetoric", "rhythm",
"ribbon", "rice", "rich", "rid", "ride", "rider", "ridge", "ridiculous",
"rifle", "right", "ring", "rise", "risk", "risky", "ritual", "rival",
"river", "road", "robot", "rock", "rocket", "role", "roll", "rolling",
"roman", "romance", "romantic", "roof", "room", "root", "rope", "rose",
"rough", "roughly", "round", "route", "routine", "routinely", "row",
"royal", "rub", "rubber", "rule", "ruling", "rumor", "run", "runner",
"running", "rural", "rush", "russian", "sacred", "sacrifice", "sad",
"safe", "safely", "safety", "sake", "salad", "salary", "sale", "sales",
"salmon", "salt", "same", "sample", "sanction", "sand", "sandwich",
"satellite", "satisfaction", "satisfy", "sauce", "save", "saving", "say",
"scale", "scandal", "scare", "scared", "scary", "scatter", "scenario",
"scene", "scent", "schedule", "scheme", "scholar", "scholarship",
"school", "science", "scientific", "scientist", "scope", "score",
"scramble", "scratch", "scream", "screen", "screening", "screw",
"script", "sculpture", "sea", "search", "season", "seat", "second",
"secondary", "secret", "secretary", "section", "sector", "secular",
"secure", "security", "see", "seed", "seek", "seem", "seemingly",
"segment", "seize", "seldom", "select", "selected", "selection", "self",
"sell", "seller", "seminar", "senate", "senator", "send", "senior",
"sensation", "sense", "sensitive", "sensitivity", "sensor", "sentence",
"sentiment", "separate", "separation", "sequence", "series", "serious",
"seriously", "servant", "serve", "service", "serving", "session",
"set", "setting", "settle", "settlement", "seven", "seventh", "several",
"severe", "severely", "sex", "sexual", "sexuality", "sexually", "shade",
"shadow", "shake", "shall", "shallow", "shame", "shape", "share",
"shared", "shareholder", "shark", "sharp", "sharply", "she", "sheep",
"sheer", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship",
"shirt", "shit", "shock", "shoe", "shoot", "shooting", "shop", "shopping",
"shore", "short", "shortage", "shortly", "shorts", "shot", "should",
"shoulder", "shout", "shove", "show", "shower", "shrimp", "shrink",
"shrug", "shut", "shuttle", "sibling", "sick", "side", "sidewalk",
"sigh", "sight", "sign", "signal", "signature", "significance",
"significant", "significantly", "silence", "silent", "silly",
"silver", "similar", "similarity", "similarly", "simple", "simply",
"simultaneously", "sin", "since", "sing", "singer", "single", "sink",
"sir", "sister", "sit", "site", "situation", "six", "sixth", "size",
"ski", "skill", "skilled", "skin", "skirt", "skull", "sky", "slave",
"slavery", "sleep", "sleeve", "slice", "slide", "slight", "slightly",
"slip", "slope", "slow", "slowly", "small", "smart", "smell", "smile",
"smoke", "smooth", "snake", "snap", "sneak", "snow", "so", "soccer",
"social", "socially", "society", "sodium", "soft", "soften", "softly",
"software", "soil", "solar", "soldier", "solely", "solid", "solution",
"solve", "some", "somebody", "someday", "somehow", "someone", "something",
"sometime", "sometimes", "somewhat", "somewhere", "son", "song", "soon",
"sophisticated", "sorry", "sort", "soul", "sound", "soup", "source",
"south", "southeast", "southern", "southwest", "sovereignty", "soviet",
"space", "spanish", "spare", "spark", "speak", "speaker", "special",
"specialist", "specialize", "specialty", "species", "specific",
"specifically", "specify", "spectacular", "spectrum", "speculate",
"speculation", "speech", "speed", "spell", "spend", "spending",
"sphere", "spill", "spin", "spine", "spirit", "spiritual", "spite",
"split", "spokesman", "sponsor", "spoon", "sport", "spot", "spouse",
"spray", "spread", "spring", "sprinkle", "squad", "square", "squeeze",
"stability", "stable", "stack", "stadium", "staff", "stage", "stair",
"stake", "stance", "stand", "standard", "standing", "star", "stare",
"start", "starter", "starting", "state", "statement", "station",
"statistical", "statistics", "statue", "status", "statute", "stay",
"steadily", "steady", "steak", "steal", "steam", "steel", "steep",
"steer", "step", "stereotype", "stick", "stiff", "still", "stimulate",
"stimulus", "stir", "stock", "stomach", "stone", "stop", "storage",
"store", "storm", "story", "stove", "straight", "straighten", "strain",
"strange", "stranger", "strategic", "strategy", "straw", "streak",
"stream", "street", "strength", "strengthen", "stress", "stretch",
"strict", "strictly", "strike", "striking", "string", "strip",
"stroke", "strong", "strongly", "structural", "structure", "struggle",
"student", "studio", "study", "stuff", "stumble", "stupid", "style",
"subject", "submit", "subsequent", "subsidy", "substance", "substantial",
"substantially", "subtle", "suburb", "suburban", "succeed", "success",
"successful", "successfully", "such", "sudden", "suddenly", "sue",
"suffer", "suffering", "sufficient", "sugar", "suggest", "suggestion",
"suicide", "suit", "suitable", "suite", "summary", "summer", "summit",
"sun", "sunlight", "sunny", "super", "superior", "supermarket",
"supervisor", "supplier", "supply", "support", "supporter", "supportive",
"suppose", "supposed", "supposedly", "supreme", "sure", "surely",
"surface", "surgeon", "surgery", "surprise", "surprised", "surprising",
"surprisingly", "surround", "surrounding", "surveillance", "survey",
"survival", "survive", "survivor", "suspect", "suspend", "suspicion",
"suspicious", "sustain", "sustainable", "swallow", "swear", "sweat",
"sweater", "sweep", "sweet", "swell", "swim", "swimming", "swing",
"switch", "sword", "symbol", "symbolic", "sympathy", "symptom",
"syndrome", "system", "table", "tablespoon", "tackle", "tactic",
"tail", "take", "tale", "talent", "talented", "talk", "tall",
"tank", "tap", "tape", "target", "task", "taste", "tax", "taxpayer",
"tea", "teach", "teacher", "teaching", "team", "teammate", "tear",
"teaspoon", "technical", "technician", "technique", "technological",
"technology", "teen", "teenage", "teenager", "telephone", "telescope",
"television", "tell", "temperature", "temple", "temporary", "ten",
"tend", "tendency", "tender", "tennis", "tension", "tent", "term",
"terms", "terrain", "terrible", "terribly", "terrific", "territory",
"terror", "terrorism", "terrorist", "test", "testify", "testimony",
"testing", "text", "textbook", "texture", "than", "thank", "thanks",
"thanksgiving", "that", "the", "theater", "their", "them", "theme",
"themselves", "then", "theological", "theology", "theoretical", "theory",
"therapist", "therapy", "there", "thereby", "therefore", "these", "they",
"thick", "thigh", "thin", "thing", "think", "thinking", "third", "thirty",
"this", "thoroughly", "those", "though", "thought", "thousand", "thread",
"threat", "threaten", "three", "threshold", "thrive", "throat", "through",
"throughout", "throw", "thumb", "thus", "ticket", "tie", "tight",
"tighten", "tightly", "timber", "time", "timing", "tiny", "tip", "tire",
"tired", "tissue", "title", "to", "tobacco", "today", "toe", "together",
"toilet", "tolerance", "tolerate", "tomato", "tomorrow", "tone", "tongue",
"tonight", "too", "tool", "tooth", "top", "topic", "toss", "total",
"totally", "touch", "touchdown", "tough", "tour", "tourism", "tourist",
"tournament", "toward", "towards", "towel", "tower", "town", "toxic",
"toy", "trace", "track", "trade", "trading", "tradition", "traditional",
"traditionally", "traffic", "tragedy", "tragic", "trail", "trailer",
"train", "trainer", "training", "trait", "transaction", "transfer",
"transform", "transformation", "transit", "transition", "translate",
"translation", "transmission", "transmit", "transport", "transportation",
"trash", "trauma", "travel", "traveler", "treasure", "treat", "treatment",
"treaty", "tree", "tremendous", "trend", "trial", "tribal", "tribe",
"trick", "trigger", "trip", "triumph", "troop", "tropical", "trouble",
"troubled", "truck", "true", "truly", "trunk", "trust", "truth", "try",
"tube", "tumor", "tunnel", "turkey", "turn", "tv", "twelve", "twentieth",
"twenty", "twice", "twin", "twist", "two", "type", "typical", "typically",
"ugly", "ultimate", "ultimately", "unable", "uncertain", "uncertainty",
"uncle", "uncomfortable", "uncover", "under", "undergo", "undergraduate",
"underlying", "undermine", "understand", "understanding", "undertake",
"unemployment", "unexpected", "unfair", "unfold", "unfortunately",
"unhappy", "uniform", "union", "unique", "unit", "unite", "united",
"unity", "universal", "universe", "university", "unknown", "unless",
"unlike", "unlikely", "unprecedented", "until", "unusual", "up",
"update", "upon", "upper", "upset", "upstairs", "urban", "urge",
"us", "use", "used", "useful", "user", "usual", "usually", "utility",
"utilize", "vacation", "vaccine", "vacuum", "valid", "validity",
"valley", "valuable", "value", "vanish", "variable", "variation",
"variety", "various", "vary", "vast", "vegetable", "vehicle", "vendor",
"venture", "verbal", "verdict", "version", "versus", "vertical", "very",
"vessel", "veteran", "via", "victim", "victory", "video", "view",
"viewer", "village", "violate", "violation", "violence", "violent",
"virtual", "virtually", "virtue", "virus", "visible", "vision", "visit",
"visitor", "visual", "vital", "vitamin", "vocal", "voice", "volume",
"voluntary", "volunteer", "vote", "voter", "voting", "vs", "vulnerable",
"wage", "wagon", "waist", "wait", "wake", "walk", "walking", "wall",
"wander", "want", "war", "warehouse", "warm", "warmth", "warn", "warning",
"warrior", "wash", "waste", "watch", "water", "wave", "way", "we", "weak",
"weaken", "weakness", "wealth", "wealthy", "weapon", "wear", "weather",
"weave", "wedding", "week", "weekend", "weekly", "weigh", "weight",
"weird", "welcome", "welfare", "well", "west", "western", "wet", "whale",
"what", "whatever", "wheat", "wheel", "wheelchair", "when", "whenever",
"where", "whereas", "wherever", "whether", "which", "while", "whisper",
"white", "who", "whoever", "whole", "whom", "whose", "why", "wide",
"widely", "widespread", "widow", "wife", "wild", "wilderness", "wildlife",
"will", "willing", "willingness", "win", "wind", "window", "wine", "wing",
"winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "with",
"withdraw", "withdrawal", "within", "without", "witness", "woman",
"wonder", "wonderful", "wood", "wooden", "word", "work", "worker",
"working", "workout", "workplace", "works", "workshop", "world",
"worldwide", "worried", "worry", "worth", "would", "wound", "wrap",
"wrist", "write", "writer", "writing", "written", "wrong", "yard",
"yeah", "year", "yell", "yellow", "yes", "yesterday", "yet", "yield",
"you", "young", "youngster", "your", "yours", "yourself", "youth", "zone" ]

# initialize variables

hanged=0
saved=0
perfectly=0

for word in ALLWORDS :
    if len(word) >= minsize :
        WORDS.append(word)

do_more = 'y'
while (do_more.lower() == 'y') :
    clear_all= "\n" * 100
    word=""
    abandon="XQ"

    if len(WORDS) < 1 :
        print "\n\nI'm sorry.  There are no words left in my list with %d or more characters." % minsize
        break

    word = random.choice(WORDS)   # the word to be guessed

    WORDS.remove(word)   # don't play this word again for this session

    so_far = "." * len(word)   # one dot for each letter in word to be guessed

    wrong = 0                  # number of wrong guesses player has made

    used = []                  # letters already guessed

    print "Welcome to Hangman. Good luck!"

    while (wrong < MAX_WRONG) and (so_far != word):
        print clear_all
        print HANGMAN[wrong]
        print "\nYou've used the following letters:\n", used
        print "\nSo far, the word is:\n", so_far

        print "\n\n"

        guess = ""
        while (
                (guess not in list(set(string.ascii_lowercase)))
            or
                (guess in used)
            ) :
            guess = raw_input("Enter your guess: ")
            if (guess in abandon):
                exit
            guess = guess.lower()
            if (guess in used) :
                print guess , "was already guessed. ",

        used.append(guess)
        used.sort()

        if (guess in word):

           print "\nYes!", guess, "is in the word!"

           # create a new so_far to include guess
           new = ""
           for i in range(len(word)):
               if guess == word[i]:
                   new += guess
               else:
                   new += so_far[i]
           so_far = new

        else:
            print "\nSorry,", guess, "isn't in the word."
            wrong += 1

    print clear_all

    if (wrong == MAX_WRONG):
        print HANGMAN[wrong]
        print "\nYour man's been hanged!"
        hanged += 1
    elif (wrong == 0):
        print PERFECT
        print "\n\n\n\n\nYou guessed it with NO MISSES!"
        saved += 1
        perfectly += 1
    else:
        print SAVEMAN
        print "\n\n\n\n\nYou guessed it!"
        saved += 1

    print "\nThe word was: ", word.upper()

    print "\nSo far, you have hanged %d and saved %d" % (hanged, saved),
    if (perfectly > 0):
        print "(%d perfectly!)" % perfectly
    else:
        print ""

    if len(WORDS) > 0 :
        do_more=raw_input("\n\nAnother word? ")
        if (len(do_more) > 1):
            do_more=do_more[0]
        do_more=do_more.lower()
        


