#!/bin/ksh

PATTERN=${1:-@-}

SIZE=0
until read -t$(( $SIZE * .05 ))
do
COLOR=$(( ($RANDOM % 6)+1 ))
SIZE=$(( (RANDOM % 11) + 1))
yes 2>/dev/null | sed ${SIZE}q | ksh thue_morse_color.ksh "$PATTERN" $COLOR | tr -d '\012'
done
