#!/usr/bin/env bash
############################################################################## 
#	$Header$
#
#	NAME		TITLE
#	zounds		Jerry Maguire's Shakespearean Insulter
#
#	SYNOPSIS
#	zounds [-x] [count]
#	count is number of insults to generate; defaults to 1
#	
#	DESCRIPTION
#	An English teacher at Center Grove High School in Greenwood Indiana
#	named Jerry Maguire appears to be the originating author of this list
#	of Shakespearean insults.  It has been circulating around the internet
#	since at least 1996, mosty without attribution.  The concept is simple
#	enough - take a simple adjective from list 1, a compound adjective from
#	list 2, and a noun from list 3, prefix with "Thou" and behold - an
#	insult worthy of (or at least sounding a bit like) the Bard.
#
#	Thanks to Chris Seidel (with Lara M) for providing an attribution for
#	the original list at
#	http://www.pangloss.com/seidel/shake_rule.html.  In appreciation, this
#	script will include Seidel's additions if invoked with the -x "extended
#	insults" option.
#	
#	RETURN VALUE
#	none meaningful
#	
#	NOTES / CAVEATS
#		
#	AUTHOR, REVIEWER
#	Leif Fellague - Wed Nov 30 2016
#
#	$Log$
#		
##############################################################################

SEIDEL=""

USAGE="
${0##*/} [-x] [count]

Generate Shakespeare-style insults (just one if no count provided).  The -x
option will include Chris Seidel's additions to the 'classic' insult lists.
"

while getopts :x optc
do
	case $optc in
		x)	SEIDEL=true ;;
		*)	echo "$USAGE" >&2
			exit 1
			;;
	esac
done
shift $(( $OPTIND - 1 ))

typeset -i NBR
if [ "$1" -gt 0 ] 2>/dev/null
then
	NBR=$1
else
	NBR=1
fi

ADJ1=(
	artless bawdy beslubbering bootless churlish
	cockered clouted craven currish dankish
	dissembling droning errant fawning fobbing froward
	frothy gleeking goatish gorbellied impertinent infectious
	jarring loggerheaded lumpish mammering mangled mewling paunchy
	pribbling puking puny qualling rank reeky roguish
	ruttish saucy spleeny spongy surly tottering unmuzzled
	vain venomed villainous warped wayward weedy
	yeasty
	)

ADJ2=(
	base-court bat-fowling beef-witted beetle-headed boil-brained
	clapper-clawed clay-brained common-kissing crook-pated dismal-dreaming
	dizzy-eyed doghearted dread-bolted earth-vexing elf-skinned
	fat-kidneyed fen-sucked flap-mouthed fly-bitten folly-fallen fool-born
	full-gorged guts-griping half-faced hasty-witted hedge-born hell-hated
	idle-headed ill-breeding ill-nurtured knotty-pated milk-livered
	motley-minded onion-eyed plume-plucked pottle-deep pox-marked
	reeling-ripe rough-hewn rude-growing rump-fed shard-borne sheep-biting
	spur-galled swag-bellied tardy-gaited tickle-brained toad-spotted
	unchin-snouted weather-bitten 
	)

NOUN=(
	apple-john baggage barnacle bladder boar-pig bugbear bum-bailey
	canker-blossom clack-dish clotpole coxcomb codpiece death-token
	dewberry flap-dragon flax-wench flirt-gill foot-licker fustilarian
	giglet gudgeon haggard harpy hedge-pig horn-beast hugger-mugger
	joithead lewdster lout maggot-pie malt-worm mammet measle minnow
	miscreant moldwarp mumble-news nut-hook pigeon-egg pignut puttock
	pumpion ratsbane scut skainsmate strumpet varlot vassal whey-face
	wagtail
	)

if [ "$SEIDEL" ]
then
ADJ1=( "${ADJ1[@]}"
	cullionly fusty caluminous wimpled burly-boned misbegotten
	odiferous poisonous fishified wart-necked
	)

ADJ2=( "${ADJ2[@]}"
	whoreson malmsey-nosed rampallian lily-livered scurvy-valiant
	brazen-faced "unwash'd" "bunch-back'd" leaden-footed muddy-mettled
	"pigeon-liver'd" scale-sided
	)

NOUN=( "${NOUN[@]}"
	knave blind-worm popinjay scullian jolt-head malcontent devil-monk toad
	rascal basket-kockle
	)
fi

while [ $NBR -gt 0 ]
do
	echo "Thou \
${ADJ1[RANDOM%${#ADJ1[*]}]} \
${ADJ2[RANDOM%${#ADJ2[*]}]} \
${NOUN[RANDOM%${#NOUN[*]}]}!"
	NBR=${NBR}-1
done

##############################################################################
#	EOF $Source$
##############################################################################
